### ISSUE TITLE
Null dereference?

### ISSUE THREAD

**Issue by 360CodeSafe** [vergoh/vnstat#100]
src/ibw.c  

in line 136: p = ibwgetnode(iface);  return null pointer. 

ibwnode *ibwgetnode(const char *iface)
{
	ibwnode *p = ifacebw;

	while (p != NULL) {
		if (strcasecmp(p->interface, iface)==0) {
			return p;
		}
		p = p->next;
	}
	return NULL;  //
}

in line 139: p->limit = speed; // access to field 'limit' results in a dereference of a null pointer (loaded from variable 'p')

**Comment by vergoh** [comment]
Thanks, that's a valid finding. This scenario is indeed possible if the ``ibwadd()`` call on line 135 fails to malloc.
