### ISSUE TITLE
vnstat 2.0 seems not updating database by default

### ISSUE THREAD

**Issue by Tianjie-Wu** [vergoh/vnstat#104]
SELinux is preventing vnstatd to update the database by default.
Although it may be manually turned SELinux off, or added policy module to allow this access, but it seems too complex or unsafe. is there any possibility to include a SELinux policy with the source code in the future?

**Comment by vergoh** [comment]
This Fedora bug report may also be in some way related: https://bugzilla.redhat.com/show_bug.cgi?id=1643063

Digging a little bit further leads to this discussion https://patchwork.kernel.org/patch/9833751/ which appears to suggest that there's some sort of conflict of interest between systemd and SELinux. The example service file that comes with vnStat has several of the systemd hardenings enabled mentioned in that discussion to cause issues when SELinux is also enabled. It may even be enough to disable those hardening settings from the service file to fix this issue.

The problem with including suitable policy files in the source package is that I don't have any system in regular use with SELinux enabled, I don't have a good understanding how much those policy files are distribution specific and that discussion linked above also seems to suggests that there are dependencies between SELinux and other system services existing in a distribution and release specific fashion.
