### ISSUE TITLE
Hi, Can u add a function like this: server's port's connecting ip 

### ISSUE THREAD

**Issue by ssrpanel** [vergoh/vnstat#108]
0.server 's all open port's connecting ip
1.every 60s count one times (if the timer can config , it will be awesome)
2.write to local db 

The work scene: 
I want to monitor the server's basic infomation, and want to monitor the port's connecting ip, if i found some port's connecting ip have much more what i limit, i will close the port by myself or cron job. 

THX

**Comment by vergoh** [comment]
The kernel interface vnStat uses provides only information regarding how many bytes and packets have been sent and received. Port and IP information isn't available and therefore can't be added.
