### ISSUE TITLE
Upgrading from 1.* to 2.*

### ISSUE THREAD

**Issue by gilleslamiral** [vergoh/vnstat#111]
Hi Teemu,

I've not seen any instruction or comment about using the 2.0 release on a host that runs already some 1.x release. 
Will the data be forgotten? 
Is there a way to import it?

Thanks in advance!

**Comment by vergoh** [comment]
From the CHANGES file:
```
- C struct dump database has been replaced with sqlite database,
full data import included from legacy databases of versions 1.3 - 1.18
```
Nothing will be forgotten and I intend to keep it that way. Existing databases will be imported automatically to the new database format during the first startup of the version 2.0 daemon. The yearly data will also get automatically translated from the legacy format. The old database files will be kept in place just in case you'd want to downgrade for some reason (obviously the old files no longer get updated with the version 2.0 daemon). Only the 5 minute resolution data starts from zero as nothing comparable exists in the old database.

Technically, it would also be possible to run the 1.x and 2.x daemons in parallel (obviously with different binary names) using the same database directory as the last 1.x versions are already aware of the 2.x database filename (yes, 2.0 was in development for a rather long time) and will automatically ignore it.
