### ISSUE TITLE
tests/daemon_tests.c:884:F:Daemon:waittimesync_does_not_wait_with_new_interfaces:0: Assertion 'ret==0' failed: ret==1, 0==0

### ISSUE THREAD

**Issue by brianjmurrell** [vergoh/vnstat#112]
I'm trying to build 2.0 on Ubuntu Trusty (16.04) and one of the tests fail:

```
tests/daemon_tests.c:884:F:Daemon:waittimesync_does_not_wait_with_new_interfaces:0: Assertion 'ret==0' failed: ret==1, 0==0
```

Unfortunately the test doesn't really say what it's testing.  Or rather what [waittimesync()](https://github.com/vergoh/vnstat/commit/e6a6129855efcbeda4059d8cfdc79d4e882296b6#diff-e3c34a63a3dc24d360734ba116b21622R1034) or why it might be failing.

Any ideas?

**Comment by vergoh** [comment]
That line refers to the test located in tests/daemon_tests.c and a check fails on line 884 where the expected return value is 0 but in your case it was 1.

Does it fail every time or only sometimes?
How long does the full test suite execution take?

The current implementation of that test makes some assumptions regarding how the system clock is behaving and it could be possible that the tolerance isn't large enough which could cause only this test to fail. I have several Ubuntu 16.04 servers and none have so far produced this error.

**Comment by brianjmurrell** [comment]
Fails every time.

Test execution is a second or two.

**Comment by vergoh** [comment]
Anything special (or old) with the hardware you are using?

Something, mostly a guess, that may help if changing the line 877 of tests/daemon_tests.c a little bit. There's a section with ``'-2 seconds'`` and replacing it with ``'-6 seconds'`` may provide some difference without really changing what the test itself does. Also commenting out line 868 should make more details for the error itself visible. The extra output will be in ``check_vnstat.log``.

**Comment by brianjmurrell** [comment]
> replacing it with '-6 seconds' may provide some difference 

No difference.

> commenting out line 868 should make more details for the error itself visible

```
FAIL: check_vnstat
==================

Running suite(s): vnStat
Database ":memory:" open
Database ":memory:" structure created

Processing interface "eth0"...
Unable to open: testdir/sysclassnet/eth0/speed - No such file or directory
Info: Monitoring (1): eth0 (1000 Mbit) 
datacache_status() in 0.000060 s
filldatabaselist() in 0.000072 s
w: processing eth0...
w: has 2018-11-21 20:04:29
current time:     2018-11-21 15:04:35
latest db update: 2018-11-21 20:04:29
Info: Latest database update is in the future (db: 2018-11-21 20:04:29 > now: 2018-11-21 15:04:35). Giving the system clock up to 60 minutes to sync before continuing.
99%: Checks: 302, Failures: 1, Errors: 0
tests/daemon_tests.c:884:F:Daemon:waittimesync_does_not_wait_with_new_interfaces:0: Assertion 'ret==0' failed: ret==1, 0==0

```

**Comment by vergoh** [comment]
I've replicated this behaviour by only changing the timezone of the system. The problem indeed is that this specific test doesn't work correctly if the numeric timezone has a negative value. The implementation of the daemon itself isn't affected.
