### ISSUE TITLE
man vnstat release 2.0 still describes -w, --weeks

### ISSUE THREAD

**Issue by gilleslamiral** [vergoh/vnstat#114]
Hi Teemu,

I'm reading the man pages of the release 2.0.
```
$ vnstat --version
vnStat 2.0 by Teemu Toivola <tst at iki dot fi>
```
The manal has
```
man vnstat
      -w, --weeks Show traffic for 7 days, current and previous week.
```
But 
```
$ vnstat -w
Unknown parameter "-w". Use --help for help.
$ vnstat  --weeks
Unknown parameter "--weeks". Use --help for help.
```

**Comment by vergoh** [comment]
```
$ grep -ci week *
vnstat.1:0
vnstat.conf.5:0
vnstatd.1:0
vnstati.1:0
```
Could you verify that the man page you are reading has "version 2.0" on the last line when viewed with the `man` command?

**Comment by gilleslamiral** [comment]
Well, it did replace the other binary files it didn't create. I know I did it. I knew what I was doing. Sure the scenario is not so good. I wanted to keep the start/stop scripts, the user/group setup, all those boring things that takes time to recreate manually and that were already there. That's ok, let's forget it.
