### ISSUE TITLE
RFE: scale usage

### ISSUE THREAD

**Issue by brianjmurrell** [vergoh/vnstat#115]
In a given month, the amount of data that `vnstat` says I'm using and what my ISP says I am using will differ.  Assuming the ISPs record is just not faulty (and as long as they are saying I am using less than what `vnstat` reports, I can hardly complain) I could only imagine that this is because what the ISP is counting as "data transfer" is only subset of what actually goes across my interface.  Perhaps they are not considering IP headers and only actual data/payload or somesuch.

Granted that differing packet payload sizes are going to influence the data to header ratio, over a month, a "scaling factor" can probably be pretty accurate.

It would be an interesting feature to be able to tell `vnstat` at the end of a month what ISP is reporting as the month's usage and have `vnstat` use the difference between what it calculated and what the ISP reported as a _scaling factor_ when doing estimates.

**Comment by vergoh** [comment]
There are several types of traffic that your ISP may intentionally (or not) count towards your possible quota. For example, it's possible that traffic that never leaves the ISPs internal network isn't being counted. Possibly, there's also broadcast traffic in the network that doesn't get counted. All of those are still visible to vnStat and that could explain the difference.

Have you tracked if there's any statistical correlation between what vnStat reports compared to what the ISP says on a monthly basis? I'm mainly wondering if a scaling value would even provide meaningful results.

**Comment by brianjmurrell** [comment]
I don't know yet how accurate a scaling will be.  This is my first month using `vnstat`.

I tend to feel though that a month is sufficiently long enough that a consistent scaling factor must be usable.  We'll see I guess.

Assuming it is, does this seem like a reasonable feature to add?

**Comment by vergoh** [comment]
Right now I don't see this as a very needed feature. If only a monthly report if what you are looking for then it could make more sense to write a script to read the ``--json`` output and then do the scaling based on given parameters. That would also allow having much less restrictions on how the output would then look like, for example, if the unscaled values would also be shown.
