### ISSUE TITLE
vnstat doesn't start if /var/lib/vnstat is a symlink

### ISSUE THREAD

**Issue by telsch** [vergoh/vnstat#116]
vnstat doesn't start if /var/lib/vnstat is a symlink

vnstatd -D -n
Config file: /etc/vnstat.conf
ibw list is empty.
arg 1: "-D"
arg 2: "-n"
Error: mkdir() "/var/lib/vnstat": File exists
Error: Unable to open database directory "/var/lib/vnstat": No such file or directory
Make sure it exists and is at least read enabled for current user.

**Comment by vergoh** [comment]
1. Which version of vnStat are you using?
2. Does the directory the symlink points to exist?
3. Is there some reason for using a symlink instead of setting `DatabaseDir` directly to the correct path?

**Comment by telsch** [comment]
With Ubuntu 16.04 i used vnStat 1.14 without this problem, after upgrade to 18.04 and vnStat 1.18 i run in to this.
Yes directory exists.
