### ISSUE TITLE
[features] raw bytes unit needed

### ISSUE THREAD

**Issue by thelou1s** [vergoh/vnstat#118]
Hi, I need the raw byte unit to show all numbers, that will be convenient for awk to get the traffic size without considering the 'GB' or 'MB' unit problem. Thank you for your effort.

**Comment by vergoh** [comment]
There's multiple options available (at least in the recent versions) to achieve such output:

1. `--oneline b`, most likely the easiest to parse from the command line with standard tooling
2. `--json`, usually the most suitable for script languages with json parser modules but can be a viable option also on the command line if, for example, `jq` is available
3. `--xml`, available just in case non of the above fit the needs
