### ISSUE TITLE
v2.1 - How create database? (Solus)

### ISSUE THREAD

**Issue by cantalupo555** [vergoh/vnstat#119]
![](https://i.imgur.com/MPNf1c4.png)

vnstat --add -i enp30s0

In this current version I can no longer create a database.

**Comment by vergoh** [comment]
Which install instructions did you follow the ended in this situation?

**Comment by cantalupo555** [comment]
![](https://i.imgur.com/HpCV37P.png)
I am using the package in the official Solus OS repository.
http://getsol.us/

**Comment by vergoh** [comment]
See the official INSTALL instructions: https://github.com/vergoh/vnstat/blob/master/INSTALL

I suspect the Solus OS packaging hasn't configured or started the daemon and that's why the database directory is also missing.

**Comment by cantalupo555** [comment]
I installed version 2.1 on Ubuntu 16.04 server, and it worked fine for me.

I will try to install on Solus as described in the instructions.

**Comment by vergoh** [comment]
Possibly the Solus packaging doesn't start the daemon directly. Something like `systemctl enable vnstat` followed by `systemctl start vnstat` should help or at least provide an error message if the service wasn't even installed.

**Comment by vergoh** [comment]
That `systemctl status vnstat.service` output still shows that the service is "disabled" which will result in it not starting automatically after a system reboot. You'll want to run `systemctl enable vnstat.service` to enable automatic startup of the daemon.

**Comment by cantalupo555** [comment]
![](https://i.imgur.com/90Cli3J.png)
![](https://i.imgur.com/FmJ78Gr.png)

Now it's 100%. :100: 

Solution:
```
systemctl restart vnstat
systemctl enable vnstat.service
```
Thank you @vergoh .
