### ISSUE TITLE
Interface gets deleted when rebooted

### ISSUE THREAD

**Issue by karra88** [vergoh/vnstat#126]
By default, the Ethernet interfaces are always present in the database of vnstat. 
When I am adding the SIM interface in the vnstat database, which is Point-to-Point protocol, the statistics are good until the device is up. But when the device reboots, the SIM interfaces gets deleted from database as a result there is no history of interface usage. 

The entry even doesn't show up in the vnstat configuration page in GUI 
![vnstat_config](https://user-images.githubusercontent.com/12840300/54904670-21ae1b80-4f05-11e9-8c82-6e70821b58f5.png)
but the moment the p-t-p interface is added in database, it shows up in the vnstat graphs.
![vnstat_graph](https://user-images.githubusercontent.com/12840300/54904671-2246b200-4f05-11e9-88ae-cfa5e83d9c72.png)

Did anybody face this issue ?

**Comment by vergoh** [comment]
Which version of vnStat is being used and with what distribution?

The first image suggests there's something more than the official packaging from this repository in play which may have something to do with the issue you are having. If that's the case then the issue should be reported to the correct downstream project.

**Comment by karra88** [comment]
Sorry for the late reply. 

I am using version 1.18 and it got resolved when I have added the --alwaysadd for vnstatd. 
But the interfaces are not showing up in the "Monitor Selected Interfaces". 

One more question, Can we shutdown an interface, stop sending/receiving traffic, after it reaches limit using vnstat ?

**Comment by vergoh** [comment]
vnStat by itself doesn't have the ability of taking actions if some limit is reached. However, a common solution is to use the output of `vnstat --oneline b -i interface` in a script to check if the wanted metric is greater than expected and then take actions accordingly. Having a cron entry for such script is usually the easiest option.

A simple example for a 5 GB monthly limit check:
```
#!/bin/bash
if [ $(vnstat --oneline b -i interface | cut -d\; -f11) -gt $((5*1024*1024*1024)) ]; then
  echo "taking actions, executing some relevant command here"
fi
```
Note for possible other readers of this issue: the `b` parameter for `--oneline` was introduced in version 1.18.
