### ISSUE TITLE
Error: Failed to open database "/var/lib/vnstat/vnstat.db" in read-only mode.

### ISSUE THREAD

**Issue by Arvinshu** [vergoh/vnstat#134]
i install vnstat-2.3.tar.gz in centos 7.6
this is the command i use to install vnstat:
```
# tar -zxvf  vnstat-2.3.tar.gz

# cd vnstat-2.3

# ./configure --prefix=/usr --sysconfdir=/etc

# make && make install
```

create database dir 
```
# mkdir /var/lib/vnstat

# chmod -R 777 /var/lib/vnstat/
```
at this time, i can't create database ,when i  use root  run command
```
# vnstat --add -i wlp3s0

Error: Failed to open database "/var/lib/vnstat/vnstat.db" in read-only mode.
The vnStat daemon should have created the database when started.
Check that it is configured and running. See also "man vnstatd".
```

**Comment by vergoh** [comment]
For future reference:

The install instructions are in the included INSTALL file ([INSTALL.md](https://github.com/vergoh/vnstat/blob/master/INSTALL.md) in GitHub). The instructions don't require creating the database directory (and it shouldn't be world writable anyway). Instead, the service file for the daemon needs to be manually installed after `make install` and the service started (examples for most common environments are included). The started daemon will create the necessary directories, the database and automatically populate it with currently visible interfaces.

If the included install instructions aren't clear enough, distribution specific step by step instructions for the latest release are available at https://humdi.net/wiki/vnstat.

**Comment by lalosh** [comment]
enabling and starting the service through `systemctl` solved the issue for me
```sh

$ systemctl start vnstat.service 
$ systemctl enable vnstat.service

```

**Comment by zarandija** [comment]
Thnks laosh

**Comment by ProgrammingLife** [comment]
I've solved it with:
```
cp /var/lib/vnstat/vnstat.db ~/.vnstat/
```
