### ISSUE TITLE
DatabaseDir config fail vnstat-2.4 Arch-Linux

### ISSUE THREAD

**Issue by janlambert** [vergoh/vnstat#138]
Running with DatabaseDir "/var/lib/vnstat" works fine as a systemd daemon.
Changing vnstat.conf to DatabaseDir "/var/cmn/vnstat"  fails:

Other locations also failed. Returns error 14 in dbsql.c line 70
printf("Error (debug): Can't open database \"%s\": %s\n", dbfilename, sqlite3_errmsg(db));

system journal outputs:
19:13:59->cat /root/vnstat-lib  -  ---using /var/lib/vnstat
-- Logs begin at Sat 2019-08-03 16:00:39 UTC, end at Mon 2019-09-16 18:45:46 UTC. --
-- Reboot --
Sep 16 18:45:15 XPS-13 systemd[1]: Started vnStat network traffic monitor.
Sep 16 18:45:15 XPS-13 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=vnstat comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

Sep 16 18:45:15 XPS-13 vnstatd[542]: Info: vnStat daemon 2.4 started. (pid:542 uid:0 gid:0 64-bit)
  File: /var/lib
  Size: 3488      	Blocks: 7          IO Block: 4096   directory
Device: 10307h/66311d	Inode: 388         Links: 20
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-08-09 16:15:07.169990839 +0000
Modify: 2019-09-16 17:56:07.927338934 +0000
Change: 2019-09-16 17:56:07.927338934 +0000
 Birth: -
  File: /var/lib/vnstat
  Size: 3488      	Blocks: 7          IO Block: 4096   directory
Device: 10307h/66311d	Inode: 145669      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-09-16 17:56:07.927338934 +0000
Modify: 2019-09-16 18:45:20.876666526 +0000
Change: 2019-09-16 18:45:20.876666526 +0000
 Birth: -
  File: /var/lib/vnstat/vnstat.db
  Size: 69632     	Blocks: 136        IO Block: 4096   regular file
Device: 10307h/66311d	Inode: 145688      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-09-16 18:01:00.992328553 +0000
Modify: 2019-09-16 18:45:20.876666526 +0000
Change: 2019-09-16 18:45:20.876666526 +0000
 Birth: -
Database updated: 2019-09-16 18:45:20

   wlp2s0 since 2019-09-16

          rx:  50.84 MiB      tx:  5.42 MiB      total:  56.26 MiB

   monthly
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       2019-09     50.84 MiB |    5.42 MiB |   56.26 MiB |      346 bit/s
     ------------------------+-------------+-------------+---------------
     estimated     96.41 MiB |    9.89 MiB |  106.29 MiB |

   daily
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
         today     50.84 MiB |    5.42 MiB |   56.26 MiB |    6.99 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated     65.07 MiB |    6.94 MiB |   72.02 MiB |

Using /var/cmn/vnstat
19:16:56->cat /root/vnstat-cmn
-- Logs begin at Sat 2019-08-03 16:00:39 UTC, end at Mon 2019-09-16 18:38:48 UTC. --
-- Reboot --
Sep 16 18:38:18 XPS-13 systemd[1]: Started vnStat network traffic monitor.
Sep 16 18:38:18 XPS-13 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=vnstat comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 16 18:38:18 XPS-13 vnstatd[536]: Error: Exec step failed (8: attempt to write a readonly database): "update info set value='2.4' where name='vnstatversion'"
Sep 16 18:38:18 XPS-13 vnstatd[536]: Error: Failed to open database "/var/cmn/vnstat/vnstat.db" in read/write mode.
Sep 16 18:38:18 XPS-13 systemd[1]: vnstat.service: Main process exited, code=exited, status=1/FAILURE

 File: /var/cmn
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 1030fh/66319d	Inode: 3           Links: 3
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-09-15 23:21:13.000000000 +0000
Modify: 2019-09-16 18:36:04.763089667 +0000
Change: 2019-09-16 18:36:04.763089667 +0000
 Birth: -
  File: /var/cmn/vnstat
  Size: 3488      	Blocks: 7          IO Block: 4096   directory
Device: 1030fh/66319d	Inode: 4           Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-09-16 17:56:07.927338934 +0000
Modify: 2019-09-16 18:33:17.097036721 +0000
Change: 2019-09-16 18:36:04.763089667 +0000
 Birth: -
  File: /var/cmn/vnstat/vnstat.db
  Size: 69632     	Blocks: 136        IO Block: 4096   regular file
Device: 1030fh/66319d	Inode: 5           Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-09-16 18:01:00.992328553 +0000
Modify: 2019-09-16 18:33:17.097036721 +0000
Change: 2019-09-16 18:36:04.763089667 +0000
 Birth: -

**Comment by janlambert** [comment]
Added note:
/var/cmn/vnstat/vnstat.db was cp -a from /var/lib before making the new run. It would not be created by running with the /var/cmn DatabaseDir run.

**Comment by vergoh** [comment]
Assuming I understand the [Arch build/install script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/vnstat) correctly, it appear to be using directly the systemd service file provided by the source package under examples/systemd. Check `"$pkgdir"/usr/lib/systemd/system/vnstat.service` and search for the `ReadWritePaths` keyword under the Hardening section. By default, the value is `/var/lib` which may result in everything else, including `/var/cmn/vnstat`, being made read-only. Update that to `/var/cmn`, then `systemctl daemon-reload` and restart the vnStat daemon. If I guessed correctly, that should help.

**Comment by janlambert** [comment]
Excellent Teemu!
System is now working fine and i can maintain a unified database from
two separate distros by creating a /var/cmn mountpoint. /var/lib is too
important for that.

Thanks much,
jan lambert

**Comment by vergoh** [comment]
Good to hear that helped.

When using two distros with one database, keeping in mind that the vnStat versions should stay in sync. Currently that's not really an issue with versions 2.x since there's only one database schema so all 2.x versions can read and write the same database. However, if for example #128 gets implemented then the older versions will refuse to start once the schema has been automatically upgraded by a more recent version.
