### ISSUE TITLE
Error parsing json output

### ISSUE THREAD

**Issue by red-0ne** [vergoh/vnstat#14]
We get an error when parsing `vnstat -i br0 -h --json` using `python -m json.tool`.
Indeed, the output contains some wrongly formatted json on `traffic.hours` array which contains a leading `,` (`..."hours":[,{"id":15,"...`)
```json
{"vnstatversion":"1.13","jsonversion":"1","interfaces":[{"id":"br0","nick":"br0","created":{"date":{"year":2015,"month":2,"day":8}},"updated":{"date":{"year":2015,"month":2,"day":8},"time":{"hour":15,"minutes":21}},"traffic":{"total":{"rx":974,"tx":128},"days":[{"id":0,"date":{"year":2015,"month":2,"day":8},"rx":974,"tx":128}],"months":[{"id":0,"date":{"year":2015,"month":2},"rx":974,"tx":128}],"tops":[],"hours":[,{"id":15,"date":{"year":2015,"month":2,"day":8},"rx":974,"tx":128}]}}]}
```

**Comment by vergoh** [comment]
This issue has been fixed in the current master branch and in version 1.13 should only be visible for the first 24 hours of a new database. Duplicate of issue #13.

**Comment by red-0ne** [comment]
Perfect. We'll use the master branch and consider this fixed.
