### ISSUE TITLE
Not permanently storing statistics

### ISSUE THREAD

**Issue by jamesray1** [vergoh/vnstat#143]
I've had some issues with vnstat as detailed in https://forum.manjaro.org/t/how-to-check-network-data-usage-month-by-month/107678/7

The latest issue is that it seems that data is not being permanently and on an ongoing basis being stored in the database, as it is stored for 6 5 minute intervals (30 mins) and then can no longer be retrieved.

**Comment by jamesray1** [comment]
```
➜  ~ vnstat -l
Monitoring default...    (press CTRL-C to stop)

   rx:    50.58 kbit/s    18 p/s          tx:     1.26 kbit/s     1 p/s^C


 default  /  traffic statistics

                           rx         |       tx
--------------------------------------+------------------
  bytes                     2.45 MiB  |      379.82 KiB
--------------------------------------+------------------
          max          330.21 kbit/s  |   131.25 kbit/s
      average           53.42 kbit/s  |     8.10 kbit/s
          min            5.74 kbit/s  |         0 bit/s
--------------------------------------+------------------
  packets                       9948  |            1473
--------------------------------------+------------------
          max                148 p/s  |          56 p/s
      average                 25 p/s  |           3 p/s
          min                  6 p/s  |           0 p/s
--------------------------------------+------------------
  time                  6.40 minutes
```

**Comment by jamesray1** [comment]
I've added `vnstat -l` to autostart.

**Comment by jamesray1** [comment]
On retrospect that is more of a patch fix, and would require pressing ^C to see the stats, then rerunning again if continuing a login session. Just found a similar issue in https://askubuntu.com/questions/500663/vnstat-not-updating/804118.

**Comment by jamesray1** [comment]
I made a [comment](https://askubuntu.com/questions/500663/vnstat-not-updating/804118#comment1976708_502667):

> I have the same issue, but on Manjaro Archlinux.
> `sudo chown -R vnstat:vnstat /var/lib/vnstat` outputs `chown: invalid user: ‘vnstat:vnstat’. I have only `vnstat.db` in `/var/lib/vnstat`: `-rw-r--r--  1 root root  68K Oct 23 13:07 vnstat.db`. I suppose I need to add `wlp2s0b1` this folder, although I don't know what should be in the file.

**Comment by jamesray1** [comment]
After running `systemctl restart vnstat` again ~10 minutes ago, and running `vnstat` again just now, the data is now showing for today, but without doing anything else, I expect the data will stop showing after 30 mins again, which is what happened yesterday.

**Comment by jamesray1** [comment]
```
➜  vnstat ps aux | grep vnstatd
root     22932  0.0  0.0   7456  3516 ?        Ss   13:02   0:00 /usr/sbin/vnstatd -n
jr       24123  0.0  0.0   6292  2208 pts/5    S+   13:20   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn vnstatd
```

**Comment by jamesray1** [comment]
It's still working OK.
```
➜  hcr git:(develop) vnstat -5

 wlp2s0b1  /  5 minute

         time        rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     2019-10-22
         15:00      4.32 MiB |  228.67 KiB |    4.54 MiB |  127.02 kbit/s
         15:05      9.21 MiB |  357.27 KiB |    9.56 MiB |  267.36 kbit/s
         15:10      7.01 MiB |  272.51 KiB |    7.28 MiB |  203.47 kbit/s
         15:15     29.97 MiB |    1.59 MiB |   31.56 MiB |  882.41 kbit/s
         15:20      9.66 MiB |  332.37 KiB |    9.99 MiB |  279.29 kbit/s
         15:25      4.14 MiB |   76.66 KiB |    4.21 MiB |  117.73 kbit/s
     2019-10-23
         13:00      0.99 MiB |  129.00 KiB |    1.12 MiB |   31.21 kbit/s
         13:05      1.68 MiB |   79.98 KiB |    1.75 MiB |   49.05 kbit/s
         13:10      1.39 MiB |   78.22 KiB |    1.47 MiB |   41.13 kbit/s
         13:15      1.57 MiB |   59.28 KiB |    1.62 MiB |   45.44 kbit/s
         13:20      1.97 MiB |   65.91 KiB |    2.04 MiB |   57.00 kbit/s
         13:25      1.55 MiB |   43.87 KiB |    1.59 MiB |   44.44 kbit/s
         13:30      1.73 MiB |   50.63 KiB |    1.78 MiB |   49.73 kbit/s
         13:35      1.81 MiB |   57.97 KiB |    1.86 MiB |   52.10 kbit/s
         13:40      1.64 MiB |   50.07 KiB |    1.69 MiB |   47.22 kbit/s
         13:45      5.78 MiB |  362.08 KiB |    6.13 MiB |  171.51 kbit/s
         13:50      4.64 MiB |  429.21 KiB |    5.06 MiB |  141.40 kbit/s
         13:55      2.90 MiB |  165.42 KiB |    3.06 MiB |   85.48 kbit/s
     ------------------------+-------------+-------------+---------------
```
I'll update if there's any issues. Hopefully having it in autostart will help as well.

**Comment by jamesray1** [comment]
Today it hasn't stored data as well, except until after I ran `systemctl restart vnstat`.

```
➜  ~ vnstat -5

 wlp2s0b1  /  5 minute

         time        rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     2019-10-23
         16:50      3.15 MiB |  186.54 KiB |    3.33 MiB |   93.06 kbit/s
         16:55      2.44 MiB |   49.17 KiB |    2.49 MiB |   69.53 kbit/s
         17:00      2.86 MiB |   44.88 KiB |    2.90 MiB |   81.19 kbit/s
         17:05      3.65 MiB |  203.60 KiB |    3.84 MiB |  107.50 kbit/s
         17:10      2.04 MiB |   87.90 KiB |    2.12 MiB |   59.34 kbit/s
         17:15      2.27 MiB |   88.87 KiB |    2.36 MiB |   65.95 kbit/s
         17:20      3.95 MiB |  101.97 KiB |    4.05 MiB |  113.24 kbit/s
         17:25      2.45 MiB |   74.00 KiB |    2.52 MiB |   70.40 kbit/s
         17:30      1.51 MiB |   32.49 KiB |    1.54 MiB |   43.06 kbit/s
         17:35      1.82 MiB |   48.65 KiB |    1.86 MiB |   52.10 kbit/s
         17:40      1.34 MiB |   49.62 KiB |    1.39 MiB |   38.76 kbit/s
         17:45      1.44 MiB |   80.64 KiB |    1.52 MiB |   42.44 kbit/s
         17:50      1.26 MiB |   74.59 KiB |    1.33 MiB |   37.25 kbit/s
         17:55      1.42 MiB |   45.51 KiB |    1.47 MiB |   41.02 kbit/s
         18:00      2.01 MiB |   63.30 KiB |    2.07 MiB |   57.93 kbit/s
         18:05      1.74 MiB |   54.75 KiB |    1.79 MiB |   50.03 kbit/s
         18:10      1.07 MiB |   65.23 KiB |    1.13 MiB |   31.59 kbit/s
         18:15      3.49 MiB |    1.07 MiB |    4.56 MiB |  127.39 kbit/s
         18:20      1.12 MiB |   51.70 KiB |    1.17 MiB |   32.68 kbit/s
         18:25      1.03 MiB |   62.69 KiB |    1.09 MiB |   30.55 kbit/s
         18:30      1.23 MiB |  118.94 KiB |    1.34 MiB |   37.60 kbit/s
         18:35      1.36 MiB |  211.40 KiB |    1.57 MiB |   43.87 kbit/s
     2019-10-24
         16:45    329.04 KiB |   25.50 KiB |  354.53 KiB |    9.68 kbit/s
         16:50      7.55 MiB |  201.94 KiB |    7.75 MiB |  216.58 kbit/s
     ------------------------+-------------+-------------+---------------
```
I don't think I saw from the man page, README and webpage, how to configure how long the database entries are stored for. Basically what I want is to keep tracking across boot sessions, and keep accumulating at least the total monthly data in the statistics.

As a less-than-ideal patch fix, I have added a line to `/etc/anacrontab`:
```
➜  ~ sudo cat /etc/anacrontab
[sudo] password for jr: 
# /etc/anacrontab: configuration file for anacron

# See anacron(8) and anacrontab(5) for details.

SHELL=/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
# the maximal random delay added to the base delay of the jobs
RANDOM_DELAY=3
# the jobs will be started during the following hours only
START_HOURS_RANGE=8-10

#period in days   delay in minutes   job-identifier   command
1       5       cron.daily              nice run-parts /etc/cron.daily
7       25      cron.weekly             nice run-parts /etc/cron.weekly
@monthly 45     cron.monthly            nice run-parts /etc/cron.monthly
@daily  2       restart-vnstat          systemctl restart vnstat
➜  ~ 
```

**Comment by vergoh** [comment]
Let's start by clarifying the basics first:

1. The distribution you are using is manjaro? Any version or is it a rolling release?
2. Which version of vnStat is being used?
3. How was is installed, manually from the source package or using some distribution provided packaging?
4. Based on you comments, the `vnstatd` process appear to be started using a systemd service file. Do the service unit logs explain why it stops running? Doesn't the service file have a restart on failure policy?

I really suggest against having a cron entry doing blind restarts of the service daily. There's some reason why the daemon exits and that should be resolved.

Regarding data retention configuration, that's documented in the `vnstat.conf` man page. Search for daemon related keywords with the word "retention" in the description or look from the configuration file itself for the "data retention durations" section.

**Comment by jamesray1** [comment]
Thank you for your response!

> Based on you comments, the vnstatd process appear to be started using a systemd service file. Do the service unit logs explain why it stops running? Doesn't the service file have a restart on failure policy?

After reading https://wiki.archlinux.org/index.php/VnStat then https://wiki.archlinux.org/index.php/Systemd#Using_units, I realised what I may have done wrong. I initially only ran `systemctl start vnstat` rather than `systemctl enable vnstat`. So the service was not starting on boot. I have now ran `systemctl enable --now vnstat`. I will update after logging in and out and waiting to see if `vnstat` shows data for today (just to test that it will perform as expected).

Just before coming here, I had also added the following script (and made executable) to autostart, however that has been removed.
```
#!/bin/bash

systemctl restart vnstat >> ~/systemctl-restart-vnstat.txt
vnstat -l >> ~/vnstatl.txt

```

> 1. The distribution you are using is manjaro? Any version or is it a rolling release?

Ah yeah, sorry I forgot to include the system info, see below. Yes it's Manjaro. I don't run an update with `yay` every day, but I do update as needed and usually at least once per month. However, I have just updated it now, although only two core packages and one AUR package needed updating (not `vnstat`).

```

```

> 2. Which version of vnStat is being used?
```
➜  ~ vnstat -v
vnStat 2.4 by Teemu Toivola <tst at iki dot fi>
➜  ~ 
```

> 3. How was is installed, manually from the source package or using some distribution provided packaging?

I installed it via `yay vnstat`.

The source is here: https://www.archlinux.org/packages/community/x86_64/vnstat/. Wiki with instructions that I've followed are here: https://wiki.archlinux.org/index.php/VnStat.

> I really suggest against having a cron entry doing blind restarts of the service daily. There's some reason why the daemon exits and that should be resolved.

Agreed and the line for that in my `/etc/anacrontab` has also been removed.

> Regarding data retention configuration, that's documented in the vnstat.conf man page. Search for daemon related keywords with the word "retention" in the description or look from the configuration file itself for the "data retention durations" section.

Thank you!
