### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cantalupo555** [vergoh/vnstat#144]
I can not import, before work, now does not work.

Error: unable to open database "vnstat.db": unable to open database file

https://github.com/vergoh/vnstat/issues/120

Error: near line 3: attempt to write a readonly database
Error: near line 7: no such table: info
Error: near line 8: no such table: info
Error: near line 9: no such table: info
Error: near line 10: attempt to write a readonly database
Error: near line 21: no such table: interface
Error: near line 22: attempt to write a readonly database
Error: near line 29: no such table: fiveminute
Error: near line 30: no such table: fiveminute
Error: near line 31: no such table: fiveminute
Error: near line 32: no such table: fiveminute
Error: near line 33: no such table: fiveminute
Error: near line 34: no such table: fiveminute
Error: near line 35: no such table: fiveminute
Error: near line 36: no such table: fiveminute
Error: near line 37: no such table: fiveminute
Error: near line 38: no such table: fiveminute
Error: near line 39: no such table: fiveminute
Error: near line 40: no such table: fiveminute
Error: near line 41: no such table: fiveminute
Error: near line 42: no such table: fiveminute
Error: near line 43: no such table: fiveminute
Error: near line 44: no such table: fiveminute
Error: near line 45: no such table: fiveminute
Error: near line 46: no such table: fiveminute
Error: near line 47: no such table: fiveminute
Error: near line 48: no such table: fiveminute
Error: near line 49: no such table: fiveminute
Error: near line 50: no such table: fiveminute
Error: near line 51: no such table: fiveminute
Error: near line 52: no such table: fiveminute
Error: near line 53: no such table: fiveminute
Error: near line 54: no such table: fiveminute
Error: near line 55: no such table: fiveminute
Error: near line 56: no such table: fiveminute
Error: near line 57: no such table: fiveminute
Error: near line 58: no such table: fiveminute
Error: near line 59: no such table: fiveminute
Error: near line 60: no such table: fiveminute
Error: near line 61: no such table: fiveminute
Error: near line 62: no such table: fiveminute
Error: near line 63: no such table: fiveminute
Error: near line 64: no such table: fiveminute
Error: near line 65: no such table: fiveminute
Error: near line 66: no such table: fiveminute
Error: near line 67: no such table: fiveminute
Error: near line 68: no such table: fiveminute
Error: near line 69: no such table: fiveminute
Error: near line 70: no such table: fiveminute
Error: near line 71: no such table: fiveminute
Error: near line 72: no such table: fiveminute
Error: near line 73: no such table: fiveminute
Error: near line 74: no such table: fiveminute
Error: near line 75: no such table: fiveminute
Error: near line 76: no such table: fiveminute
Error: near line 77: no such table: fiveminute
Error: near line 78: no such table: fiveminute
Error: near line 79: no such table: fiveminute
Error: near line 80: no such table: fiveminute
Error: near line 81: no such table: fiveminute
Error: near line 82: no such table: fiveminute
Error: near line 83: no such table: fiveminute
Error: near line 84: no such table: fiveminute
Error: near line 85: no such table: fiveminute
Error: near line 86: no such table: fiveminute
Error: near line 87: no such table: fiveminute
Error: near line 88: no such table: fiveminute
Error: near line 89: no such table: fiveminute
Error: near line 90: no such table: fiveminute
Error: near line 91: no such table: fiveminute
Error: near line 92: no such table: fiveminute
Error: near line 93: no such table: fiveminute
Error: near line 94: no such table: fiveminute
Error: near line 95: no such table: fiveminute
Error: near line 96: no such table: fiveminute
Error: near line 97: no such table: fiveminute
Error: near line 98: no such table: fiveminute
Error: near line 99: no such table: fiveminute
Error: near line 100: no such table: fiveminute
Error: near line 101: no such table: fiveminute
Error: near line 102: no such table: fiveminute
Error: near line 103: no such table: fiveminute
Error: near line 104: no such table: fiveminute
Error: near line 105: no such table: fiveminute
Error: near line 106: no such table: fiveminute
Error: near line 107: no such table: fiveminute
Error: near line 108: no such table: fiveminute
Error: near line 109: no such table: fiveminute
Error: near line 110: no such table: fiveminute
Error: near line 111: no such table: fiveminute
Error: near line 112: no such table: fiveminute
Error: near line 113: no such table: fiveminute
Error: near line 114: no such table: fiveminute
Error: near line 115: no such table: fiveminute
Error: near line 116: no such table: fiveminute
Error: near line 117: no such table: fiveminute
Error: near line 118: no such table: fiveminute
Error: near line 119: no such table: fiveminute
Error: near line 120: no such table: fiveminute
Error: near line 121: no such table: fiveminute
Error: near line 122: no such table: fiveminute
Error: near line 123: no such table: fiveminute
Error: near line 124: no such table: fiveminute
Error: near line 125: no such table: fiveminute
Error: near line 126: no such table: fiveminute
Error: near line 127: no such table: fiveminute
Error: near line 128: no such table: fiveminute
Error: near line 129: no such table: fiveminute
Error: near line 130: no such table: fiveminute
Error: near line 131: no such table: fiveminute
Error: near line 132: no such table: fiveminute
Error: near line 133: no such table: fiveminute
Error: near line 134: no such table: fiveminute
Error: near line 135: no such table: fiveminute
Error: near line 136: no such table: fiveminute
Error: near line 137: no such table: fiveminute
Error: near line 138: no such table: fiveminute
Error: near line 139: no such table: fiveminute
Error: near line 140: no such table: fiveminute
Error: near line 141: no such table: fiveminute
Error: near line 142: no such table: fiveminute
Error: near line 143: no such table: fiveminute
Error: near line 144: no such table: fiveminute
Error: near line 145: no such table: fiveminute
Error: near line 146: no such table: fiveminute
Error: near line 147: no such table: fiveminute
Error: near line 148: no such table: fiveminute
Error: near line 149: no such table: fiveminute
Error: near line 150: no such table: fiveminute
Error: near line 151: no such table: fiveminute
Error: near line 152: no such table: fiveminute
Error: near line 153: no such table: fiveminute
Error: near line 154: no such table: fiveminute
Error: near line 155: no such table: fiveminute
Error: near line 156: no such table: fiveminute
Error: near line 157: no such table: fiveminute
Error: near line 158: no such table: fiveminute
Error: near line 159: no such table: fiveminute
Error: near line 160: no such table: fiveminute
Error: near line 161: no such table: fiveminute
Error: near line 162: no such table: fiveminute
Error: near line 163: no such table: fiveminute
Error: near line 164: no such table: fiveminute
Error: near line 165: no such table: fiveminute
Error: near line 166: no such table: fiveminute
Error: near line 167: no such table: fiveminute
Error: near line 168: no such table: fiveminute
Error: near line 169: no such table: fiveminute
Error: near line 170: no such table: fiveminute
Error: near line 171: no such table: fiveminute
Error: near line 172: no such table: fiveminute
Error: near line 173: no such table: fiveminute
Error: near line 174: no such table: fiveminute
Error: near line 175: no such table: fiveminute
Error: near line 176: no such table: fiveminute
Error: near line 177: no such table: fiveminute
Error: near line 178: no such table: fiveminute
Error: near line 179: no such table: fiveminute
Error: near line 180: no such table: fiveminute
Error: near line 181: no such table: fiveminute
Error: near line 182: no such table: fiveminute
Error: near line 183: no such table: fiveminute
Error: near line 184: no such table: fiveminute
Error: near line 185: no such table: fiveminute
Error: near line 186: no such table: fiveminute
Error: near line 187: no such table: fiveminute
Error: near line 188: no such table: fiveminute
Error: near line 189: no such table: fiveminute
Error: near line 190: no such table: fiveminute
Error: near line 191: no such table: fiveminute
Error: near line 192: no such table: fiveminute
Error: near line 193: no such table: fiveminute
Error: near line 194: no such table: fiveminute
Error: near line 195: no such table: fiveminute
Error: near line 196: no such table: fiveminute
Error: near line 197: no such table: fiveminute
Error: near line 198: no such table: fiveminute
Error: near line 199: no such table: fiveminute
Error: near line 200: no such table: fiveminute
Error: near line 201: no such table: fiveminute
Error: near line 202: no such table: fiveminute
Error: near line 203: no such table: fiveminute
Error: near line 204: no such table: fiveminute
Error: near line 205: no such table: fiveminute
Error: near line 206: no such table: fiveminute
Error: near line 207: no such table: fiveminute
Error: near line 208: no such table: fiveminute
Error: near line 209: no such table: fiveminute
Error: near line 210: no such table: fiveminute
Error: near line 211: no such table: fiveminute
Error: near line 212: no such table: fiveminute
Error: near line 213: no such table: fiveminute
Error: near line 214: no such table: fiveminute
Error: near line 215: no such table: fiveminute
Error: near line 216: no such table: fiveminute
Error: near line 217: no such table: fiveminute
Error: near line 218: no such table: fiveminute
Error: near line 219: no such table: fiveminute
Error: near line 220: no such table: fiveminute
Error: near line 221: no such table: fiveminute
Error: near line 222: no such table: fiveminute
Error: near line 223: no such table: fiveminute
Error: near line 224: no such table: fiveminute
Error: near line 225: no such table: fiveminute
Error: near line 226: no such table: fiveminute
Error: near line 227: no such table: fiveminute
Error: near line 228: no such table: fiveminute
Error: near line 229: no such table: fiveminute
Error: near line 230: no such table: fiveminute
Error: near line 231: no such table: fiveminute
Error: near line 232: no such table: fiveminute
Error: near line 233: no such table: fiveminute
Error: near line 234: no such table: fiveminute
Error: near line 235: no such table: fiveminute
Error: near line 236: no such table: fiveminute
Error: near line 237: no such table: fiveminute
Error: near line 238: no such table: fiveminute
Error: near line 239: no such table: fiveminute
Error: near line 240: no such table: fiveminute
Error: near line 241: no such table: fiveminute
Error: near line 242: no such table: fiveminute
Error: near line 243: no such table: fiveminute
Error: near line 244: no such table: fiveminute
Error: near line 245: no such table: fiveminute
Error: near line 246: no such table: fiveminute
Error: near line 247: no such table: fiveminute
Error: near line 248: no such table: fiveminute
Error: near line 249: no such table: fiveminute
Error: near line 250: no such table: fiveminute
Error: near line 251: no such table: fiveminute
Error: near line 252: no such table: fiveminute
Error: near line 253: no such table: fiveminute
Error: near line 254: no such table: fiveminute
Error: near line 255: no such table: fiveminute
Error: near line 256: no such table: fiveminute
Error: near line 257: no such table: fiveminute
Error: near line 258: no such table: fiveminute
Error: near line 259: no such table: fiveminute
Error: near line 260: no such table: fiveminute
Error: near line 261: no such table: fiveminute
Error: near line 262: no such table: fiveminute
Error: near line 263: no such table: fiveminute
Error: near line 264: no such table: fiveminute
Error: near line 265: no such table: fiveminute
Error: near line 266: no such table: fiveminute
Error: near line 267: no such table: fiveminute
Error: near line 268: no such table: fiveminute
Error: near line 269: no such table: fiveminute
Error: near line 270: no such table: fiveminute
Error: near line 271: no such table: fiveminute
Error: near line 272: no such table: fiveminute
Error: near line 273: no such table: fiveminute
Error: near line 274: no such table: fiveminute
Error: near line 275: no such table: fiveminute
Error: near line 276: no such table: fiveminute
Error: near line 277: no such table: fiveminute
Error: near line 278: no such table: fiveminute
Error: near line 279: no such table: fiveminute
Error: near line 280: no such table: fiveminute
Error: near line 281: no such table: fiveminute
Error: near line 282: no such table: fiveminute
Error: near line 283: no such table: fiveminute
Error: near line 284: no such table: fiveminute
Error: near line 285: no such table: fiveminute
Error: near line 286: no such table: fiveminute
Error: near line 287: no such table: fiveminute
Error: near line 288: no such table: fiveminute
Error: near line 289: no such table: fiveminute
Error: near line 290: no such table: fiveminute
Error: near line 291: no such table: fiveminute
Error: near line 292: no such table: fiveminute
Error: near line 293: no such table: fiveminute
Error: near line 294: no such table: fiveminute
Error: near line 295: no such table: fiveminute
Error: near line 296: no such table: fiveminute
Error: near line 297: no such table: fiveminute
Error: near line 298: no such table: fiveminute
Error: near line 299: no such table: fiveminute
Error: near line 300: no such table: fiveminute
Error: near line 301: no such table: fiveminute
Error: near line 302: no such table: fiveminute
Error: near line 303: no such table: fiveminute
Error: near line 304: no such table: fiveminute
Error: near line 305: no such table: fiveminute
Error: near line 306: no such table: fiveminute
Error: near line 307: no such table: fiveminute
Error: near line 308: no such table: fiveminute
Error: near line 309: no such table: fiveminute
Error: near line 310: no such table: fiveminute
Error: near line 311: no such table: fiveminute
Error: near line 312: no such table: fiveminute
Error: near line 313: no such table: fiveminute
Error: near line 314: no such table: fiveminute
Error: near line 315: no such table: fiveminute
Error: near line 316: no such table: fiveminute
Error: near line 317: no such table: fiveminute
Error: near line 318: no such table: fiveminute
Error: near line 319: no such table: fiveminute
Error: near line 320: no such table: fiveminute
Error: near line 321: no such table: fiveminute
Error: near line 322: no such table: fiveminute
Error: near line 323: no such table: fiveminute
Error: near line 324: no such table: fiveminute
Error: near line 325: no such table: fiveminute
Error: near line 326: no such table: fiveminute
Error: near line 327: no such table: fiveminute
Error: near line 328: no such table: fiveminute
Error: near line 329: no such table: fiveminute
Error: near line 330: no such table: fiveminute
Error: near line 331: no such table: fiveminute
Error: near line 332: no such table: fiveminute
Error: near line 333: no such table: fiveminute
Error: near line 334: no such table: fiveminute
Error: near line 335: no such table: fiveminute
Error: near line 336: no such table: fiveminute
Error: near line 337: no such table: fiveminute
Error: near line 338: no such table: fiveminute
Error: near line 339: no such table: fiveminute
Error: near line 340: no such table: fiveminute
Error: near line 341: no such table: fiveminute
Error: near line 342: no such table: fiveminute
Error: near line 343: no such table: fiveminute
Error: near line 344: no such table: fiveminute
Error: near line 345: no such table: fiveminute
Error: near line 346: no such table: fiveminute
Error: near line 347: no such table: fiveminute
Error: near line 348: no such table: fiveminute
Error: near line 349: no such table: fiveminute
Error: near line 350: no such table: fiveminute
Error: near line 351: no such table: fiveminute
Error: near line 352: no such table: fiveminute
Error: near line 353: no such table: fiveminute
Error: near line 354: no such table: fiveminute
Error: near line 355: no such table: fiveminute
Error: near line 356: no such table: fiveminute
Error: near line 357: no such table: fiveminute
Error: near line 358: no such table: fiveminute
Error: near line 359: no such table: fiveminute
Error: near line 360: no such table: fiveminute
Error: near line 361: no such table: fiveminute
Error: near line 362: no such table: fiveminute
Error: near line 363: no such table: fiveminute
Error: near line 364: no such table: fiveminute
Error: near line 365: no such table: fiveminute
Error: near line 366: no such table: fiveminute
Error: near line 367: no such table: fiveminute
Error: near line 368: no such table: fiveminute
Error: near line 369: no such table: fiveminute
Error: near line 370: no such table: fiveminute
Error: near line 371: no such table: fiveminute
Error: near line 372: no such table: fiveminute
Error: near line 373: no such table: fiveminute
Error: near line 374: no such table: fiveminute
Error: near line 375: no such table: fiveminute
Error: near line 376: no such table: fiveminute
Error: near line 377: no such table: fiveminute
Error: near line 378: no such table: fiveminute
Error: near line 379: no such table: fiveminute
Error: near line 380: no such table: fiveminute
Error: near line 381: no such table: fiveminute
Error: near line 382: no such table: fiveminute
Error: near line 383: no such table: fiveminute
Error: near line 384: no such table: fiveminute
Error: near line 385: no such table: fiveminute
Error: near line 386: no such table: fiveminute
Error: near line 387: no such table: fiveminute
Error: near line 388: no such table: fiveminute
Error: near line 389: no such table: fiveminute
Error: near line 390: no such table: fiveminute
Error: near line 391: no such table: fiveminute
Error: near line 392: no such table: fiveminute
Error: near line 393: no such table: fiveminute
Error: near line 394: no such table: fiveminute
Error: near line 395: no such table: fiveminute
Error: near line 396: no such table: fiveminute
Error: near line 397: no such table: fiveminute
Error: near line 398: no such table: fiveminute
Error: near line 399: no such table: fiveminute
Error: near line 400: no such table: fiveminute
Error: near line 401: no such table: fiveminute
Error: near line 402: no such table: fiveminute
Error: near line 403: no such table: fiveminute
Error: near line 404: no such table: fiveminute
Error: near line 405: no such table: fiveminute
Error: near line 406: no such table: fiveminute
Error: near line 407: no such table: fiveminute
Error: near line 408: no such table: fiveminute
Error: near line 409: no such table: fiveminute
Error: near line 410: no such table: fiveminute
Error: near line 411: no such table: fiveminute
Error: near line 412: no such table: fiveminute
Error: near line 413: no such table: fiveminute
Error: near line 414: no such table: fiveminute
Error: near line 415: no such table: fiveminute
Error: near line 416: no such table: fiveminute
Error: near line 417: no such table: fiveminute
Error: near line 418: no such table: fiveminute
Error: near line 419: no such table: fiveminute
Error: near line 420: no such table: fiveminute
Error: near line 421: no such table: fiveminute
Error: near line 422: no such table: fiveminute
Error: near line 423: no such table: fiveminute
Error: near line 424: no such table: fiveminute
Error: near line 425: no such table: fiveminute
Error: near line 426: no such table: fiveminute
Error: near line 427: no such table: fiveminute
Error: near line 428: no such table: fiveminute
Error: near line 429: no such table: fiveminute
Error: near line 430: no such table: fiveminute
Error: near line 431: no such table: fiveminute
Error: near line 432: no such table: fiveminute
Error: near line 433: no such table: fiveminute
Error: near line 434: no such table: fiveminute
Error: near line 435: no such table: fiveminute
Error: near line 436: no such table: fiveminute
Error: near line 437: no such table: fiveminute
Error: near line 438: no such table: fiveminute
Error: near line 439: no such table: fiveminute
Error: near line 440: no such table: fiveminute
Error: near line 441: no such table: fiveminute
Error: near line 442: no such table: fiveminute
Error: near line 443: no such table: fiveminute
Error: near line 444: no such table: fiveminute
Error: near line 445: no such table: fiveminute
Error: near line 446: no such table: fiveminute
Error: near line 447: no such table: fiveminute
Error: near line 448: no such table: fiveminute
Error: near line 449: no such table: fiveminute
Error: near line 450: no such table: fiveminute
Error: near line 451: no such table: fiveminute
Error: near line 452: no such table: fiveminute
Error: near line 453: no such table: fiveminute
Error: near line 454: no such table: fiveminute
Error: near line 455: no such table: fiveminute
Error: near line 456: no such table: fiveminute
Error: near line 457: no such table: fiveminute
Error: near line 458: no such table: fiveminute
Error: near line 459: no such table: fiveminute
Error: near line 460: no such table: fiveminute
Error: near line 461: no such table: fiveminute
Error: near line 462: no such table: fiveminute
Error: near line 463: no such table: fiveminute
Error: near line 464: no such table: fiveminute
Error: near line 465: no such table: fiveminute
Error: near line 466: no such table: fiveminute
Error: near line 467: no such table: fiveminute
Error: near line 468: no such table: fiveminute
Error: near line 469: no such table: fiveminute
Error: near line 470: no such table: fiveminute
Error: near line 471: no such table: fiveminute
Error: near line 472: no such table: fiveminute
Error: near line 473: no such table: fiveminute
Error: near line 474: no such table: fiveminute
Error: near line 475: no such table: fiveminute
Error: near line 476: no such table: fiveminute
Error: near line 477: no such table: fiveminute
Error: near line 478: no such table: fiveminute
Error: near line 479: no such table: fiveminute
Error: near line 480: no such table: fiveminute
Error: near line 481: no such table: fiveminute
Error: near line 482: no such table: fiveminute
Error: near line 483: no such table: fiveminute
Error: near line 484: no such table: fiveminute
Error: near line 485: no such table: fiveminute
Error: near line 486: no such table: fiveminute
Error: near line 487: no such table: fiveminute
Error: near line 488: no such table: fiveminute
Error: near line 489: no such table: fiveminute
Error: near line 490: no such table: fiveminute
Error: near line 491: no such table: fiveminute
Error: near line 492: no such table: fiveminute
Error: near line 493: no such table: fiveminute
Error: near line 494: no such table: fiveminute
Error: near line 495: no such table: fiveminute
Error: near line 496: no such table: fiveminute
Error: near line 497: no such table: fiveminute
Error: near line 498: no such table: fiveminute
Error: near line 499: no such table: fiveminute
Error: near line 500: no such table: fiveminute
Error: near line 501: no such table: fiveminute
Error: near line 502: no such table: fiveminute
Error: near line 503: no such table: fiveminute
Error: near line 504: no such table: fiveminute
Error: near line 505: no such table: fiveminute
Error: near line 506: no such table: fiveminute
Error: near line 507: no such table: fiveminute
Error: near line 508: no such table: fiveminute
Error: near line 509: no such table: fiveminute
Error: near line 510: no such table: fiveminute
Error: near line 511: no such table: fiveminute
Error: near line 512: no such table: fiveminute
Error: near line 513: no such table: fiveminute
Error: near line 514: no such table: fiveminute
Error: near line 515: attempt to write a readonly database
Error: near line 522: no such table: hour
Error: near line 523: no such table: hour
Error: near line 524: no such table: hour
Error: near line 525: no such table: hour
Error: near line 526: no such table: hour
Error: near line 527: no such table: hour
Error: near line 528: no such table: hour
Error: near line 529: no such table: hour
Error: near line 530: no such table: hour
Error: near line 531: no such table: hour
Error: near line 532: no such table: hour
Error: near line 533: no such table: hour
Error: near line 534: no such table: hour
Error: near line 535: no such table: hour
Error: near line 536: no such table: hour
Error: near line 537: no such table: hour
Error: near line 538: no such table: hour
Error: near line 539: no such table: hour
Error: near line 540: no such table: hour
Error: near line 541: no such table: hour
Error: near line 542: no such table: hour
Error: near line 543: no such table: hour
Error: near line 544: no such table: hour
Error: near line 545: no such table: hour
Error: near line 546: no such table: hour
Error: near line 547: no such table: hour
Error: near line 548: no such table: hour
Error: near line 549: no such table: hour
Error: near line 550: no such table: hour
Error: near line 551: no such table: hour
Error: near line 552: no such table: hour
Error: near line 553: no such table: hour
Error: near line 554: no such table: hour
Error: near line 555: no such table: hour
Error: near line 556: no such table: hour
Error: near line 557: no such table: hour
Error: near line 558: no such table: hour
Error: near line 559: no such table: hour
Error: near line 560: no such table: hour
Error: near line 561: no such table: hour
Error: near line 562: no such table: hour
Error: near line 563: no such table: hour
Error: near line 564: no such table: hour
Error: near line 565: no such table: hour
Error: near line 566: no such table: hour
Error: near line 567: no such table: hour
Error: near line 568: no such table: hour
Error: near line 569: no such table: hour
Error: near line 570: no such table: hour
Error: near line 571: no such table: hour
Error: near line 572: no such table: hour
Error: near line 573: no such table: hour
Error: near line 574: no such table: hour
Error: near line 575: no such table: hour
Error: near line 576: no such table: hour
Error: near line 577: no such table: hour
Error: near line 578: no such table: hour
Error: near line 579: no such table: hour
Error: near line 580: no such table: hour
Error: near line 581: no such table: hour
Error: near line 582: no such table: hour
Error: near line 583: no such table: hour
Error: near line 584: no such table: hour
Error: near line 585: no such table: hour
Error: near line 586: no such table: hour
Error: near line 587: no such table: hour
Error: near line 588: no such table: hour
Error: near line 589: no such table: hour
Error: near line 590: no such table: hour
Error: near line 591: no such table: hour
Error: near line 592: no such table: hour
Error: near line 593: no such table: hour
Error: near line 594: no such table: hour
Error: near line 595: no such table: hour
Error: near line 596: no such table: hour
Error: near line 597: no such table: hour
Error: near line 598: no such table: hour
Error: near line 599: no such table: hour
Error: near line 600: no such table: hour
Error: near line 601: no such table: hour
Error: near line 602: no such table: hour
Error: near line 603: no such table: hour
Error: near line 604: no such table: hour
Error: near line 605: no such table: hour
Error: near line 606: no such table: hour
Error: near line 607: no such table: hour
Error: near line 608: no such table: hour
Error: near line 609: no such table: hour
Error: near line 610: no such table: hour
Error: near line 611: no such table: hour
Error: near line 612: attempt to write a readonly database
Error: near line 619: no such table: day
Error: near line 620: no such table: day
Error: near line 621: no such table: day
Error: near line 622: no such table: day
Error: near line 623: no such table: day
Error: near line 624: no such table: day
Error: near line 625: no such table: day
Error: near line 626: no such table: day
Error: near line 627: no such table: day
Error: near line 628: no such table: day
Error: near line 629: no such table: day
Error: near line 630: no such table: day
Error: near line 631: no such table: day
Error: near line 632: no such table: day
Error: near line 633: no such table: day
Error: near line 634: no such table: day
Error: near line 635: no such table: day
Error: near line 636: no such table: day
Error: near line 637: no such table: day
Error: near line 638: no such table: day
Error: near line 639: no such table: day
Error: near line 640: no such table: day
Error: near line 641: no such table: day
Error: near line 642: no such table: day
Error: near line 643: no such table: day
Error: near line 644: no such table: day
Error: near line 645: no such table: day
Error: near line 646: no such table: day
Error: near line 647: no such table: day
Error: near line 648: no such table: day
Error: near line 649: no such table: day
Error: near line 650: no such table: day
Error: near line 651: no such table: day
Error: near line 652: no such table: day
Error: near line 653: no such table: day
Error: near line 654: no such table: day
Error: near line 655: no such table: day
Error: near line 656: no such table: day
Error: near line 657: no such table: day
Error: near line 658: no such table: day
Error: near line 659: no such table: day
Error: near line 660: no such table: day
Error: near line 661: no such table: day
Error: near line 662: no such table: day
Error: near line 663: no such table: day
Error: near line 664: no such table: day
Error: near line 665: no such table: day
Error: near line 666: no such table: day
Error: near line 667: no such table: day
Error: near line 668: no such table: day
Error: near line 669: no such table: day
Error: near line 670: no such table: day
Error: near line 671: no such table: day
Error: near line 672: no such table: day
Error: near line 673: no such table: day
Error: near line 674: no such table: day
Error: near line 675: no such table: day
Error: near line 676: no such table: day
Error: near line 677: no such table: day
Error: near line 678: no such table: day
Error: near line 679: no such table: day
Error: near line 680: no such table: day
Error: near line 681: no such table: day
Error: near line 682: attempt to write a readonly database
Error: near line 689: no such table: month
Error: near line 690: no such table: month
Error: near line 691: no such table: month
Error: near line 692: no such table: month
Error: near line 693: no such table: month
Error: near line 694: no such table: month
Error: near line 695: no such table: month
Error: near line 696: no such table: month
Error: near line 697: no such table: month
Error: near line 698: attempt to write a readonly database
Error: near line 705: no such table: year
Error: near line 706: attempt to write a readonly database
Error: near line 713: no such table: top
Error: near line 714: no such table: top
Error: near line 715: no such table: top
Error: near line 716: no such table: top
Error: near line 717: no such table: top
Error: near line 718: no such table: top
Error: near line 719: no such table: top
Error: near line 720: no such table: top
Error: near line 721: no such table: top
Error: near line 722: no such table: top
Error: near line 723: no such table: top
Error: near line 724: no such table: top
Error: near line 725: no such table: top
Error: near line 726: no such table: top
Error: near line 727: no such table: top
Error: near line 728: no such table: top
Error: near line 729: no such table: top
Error: near line 730: no such table: top
Error: near line 731: no such table: top
Error: near line 732: no such table: top
Error: near line 733: no such table: top

**Comment by vergoh** [comment]
`unable to open database file` suggests any (or none) of the following could be possible:

1. The file you are trying to use is wrong and doesn't exist
2. `vnstatd` is still running and has a lock for the file
3. You don't have necessary permission for modifying the file

**Comment by cantalupo555** [comment]
Thank you.

sudo su

resolved
