### ISSUE TITLE
JSON and XML output not working with mode and limit parameters together

### ISSUE THREAD

**Issue by janh** [vergoh/vnstat#149]
With vnStat 2.5, JSON and XML output no longer works when both the mode and limit parameter are given. This is due to changes in argument parsing.

The command `vnstat --json f 1` (which worked with vnStat 2.4) now just prints:
`Unknown parameter "1". Use --help for help.`

Specifying just a mode or just a limit still works.

**Comment by vergoh** [comment]
Thanks for the quick report. It looks like I managed to break that functionality while refactoring the argument parser to make it unit testable (the old version had zero tests) but, for some reason, missed that scenario without adding any `--limit` or similar as alternative.

I'll get this fixed and consider releasing 2.6 during the weekend if nothing else shows up. Probably I should move later also to major.minor.patch versioning as 2.5 is more like 2.4.1 and 2.6 would be better as 2.4.2. However, without a 2.4.0, I don't feel this would be a good time to change also the versioning.
