### ISSUE TITLE
Question/Feature Request re IPv6

### ISSUE THREAD

**Issue by seamusdemora** [vergoh/vnstat#163]
Thanks for this great package. I used it some time ago, and I've just re-installed it on a Raspberry Pi for the purpose of measuring the relative amounts of IPv4 vs IPv6 traffic. Unfortunately, after a quick perusal of the manual, it seems `vnstat` doesn't have that capability... is that correct, or have I overlooked something? 

If not, please take this as a feature request: I would like to use `vnstat` to track IPv4 and IPv6 traffic separately.

**Comment by seamusdemora** [comment]
Was this a stupid question? Did I overlook something obvious?

**Comment by cgzones** [comment]
I think vnStat does not support to breakdown the traffic into protocols.
It reads the generic transmission data from the kernel, compound of ipv4/ipv6/icmp/arp...

With nftables you can split traffic into protocols and measure it with the `counter` statement.

**Comment by seamusdemora** [comment]
Thanks - I'll give it a look.

**Comment by vergoh** [comment]
There aren't stupid questions, not at least in this project. However, there's no separate dedicated support crew either as this is more of a one person hobby / free time project. Sorry for the reply delay.

vnStat, in Linux, uses the `/proc/net/dev` kernel provided file as its primary data source and `/sys/class/net/` as secondary backup. Those sources don't provide any information about the used protocols or transports. As a result, tracking the IPv4 / IPv6 usage is something vnStat can't do without using some other data source and that's something I feel isn't within the scope of vnStat.
