### ISSUE TITLE
Problem adding interface

### ISSUE THREAD

**Issue by alo0oz** [vergoh/vnstat#165]
OS: archlabs
Kernel: archlinux 5.6.15-zen2-1-zen
vnstat version: 2.6
Vnstat ouput: 
```
vnstat --add -i enp0s20u1
Adding interface "enp0s20u1" for monitoring to database...
Error: Exec step failed (8: attempt to write a readonly database): "insert into interface (name, active, created, updated, rxcounter, txcounter, rxtotal, txtotal) values ('enp0s20u1', 1, datetime('now', 'localtime'), datetime('now', 'localtime'), 0, 0, 0, 0)"
Error: Adding interface "enp0s20u1" to database failed.
```
Thanks in advance

**Comment by vergoh** [comment]
1. Which user are you using to execute that `--add` command?
2. Which user owns `/var/lib/vnstat/vnstat.db`?

**Comment by vergoh** [comment]
Closing due to lack of necessary information for understanding the issue. Feel free to reopen if more information can be provided.
