### ISSUE TITLE
Format change after removing interface.

### ISSUE THREAD

**Issue by foo2rama** [vergoh/vnstat#172]
I ran into a weird issue where the format completely changed once I pull out the unused wlan0 adapter.

I preferred the previous formatting when I was putting into my nightly log files.

Attached you can see the change with the command run before and after the removal of the adapter.
[vnstatformetchange.txt](https://github.com/vergoh/vnstat/files/5336361/vnstatformetchange.txt)

**Comment by vergoh** [comment]
vnStat uses a shorter format when there are multiple interfaces available and the longer format when there's only one interface in the database or specific interface has been requested. You can however still get the shorter format using `-s` or `--short` parameter on the command line or changing the `QueryMode` setting in the configuration file from the default `0` to `5`.

**Comment by foo2rama** [comment]
Thanks that solved it, I did not see that in the config file, I must have missed it.  Thanks!
