### ISSUE TITLE
Per User Bandwidth Logging

### ISSUE THREAD

**Issue by plutocrat** [vergoh/vnstat#176]
I have no idea if this is even possible, but if it is, then consider it a feature request. If it isn't, then please point me in the direction of any resources that might have such functionality. 

It is very simply the ability to log the user along with the associated bandwidth, so that excessive usage can be attributed. I'm aware of nethogs. I guess it would be similar to that, but with the data logged to a database instead of live display.

**Comment by vergoh** [comment]
Sorry, that's something that isn't possible for vnStat. The available data source provides no information regarding which user or application is using the bandwidth nor the source or destination either.

**Comment by plutocrat** [comment]
No problem. You never know if you don't ask! Thanks for a useful tool.
