### ISSUE TITLE
vnstat counts intranet traffic ?

### ISSUE THREAD

**Issue by stilleshan** [vergoh/vnstat#180]
My server had mount a volume by iscsi. vnstat counts intranet traffic ?

All data write and read has been counts in vnstat .

How to configure it to ignore intranet traffic?

**Comment by vergoh** [comment]
It's not possible to filter traffic based on its source or destination as the data source used by vnStat doesn't offer such option. The only workaround would be to have a separate network interface towards intranet.

**Comment by stilleshan** [comment]
Thanks for help.
