### ISSUE TITLE
Zero data inhibits database update timestamp

### ISSUE THREAD

**Issue by mrjoel** [vergoh/vnstat#190]
When using in a configuration with multiple optional network adapters, it is common for us to have some network adapters never used and thus always have zero cumulative data. For these the message "Not enough data available yet." is shown, which is reasonable. However, when this message prints it prevents the summary message from being shown which indicated last database update timestamp ("Database updated:").

**Comment by vergoh** [comment]
Which version of vnStat is being used?

**Comment by mrjoel** [comment]
This is with vnStat 2.6 as built and shipped with OpenWRT.

**Comment by vergoh** [comment]
I was able to replicate the behaviour in a virtual machine by having several interfaces configured but only few connected. Assuming the default configuration is used and `TrafficlessEntries` has a value of `1` as a result, interfaces that don't see any traffic will still get database entries created for all time resolutions so it indeed doesn't look totally correct to show "Not enough data available yet." in such situation.

I'll try to find some better test for the interface activity than checking if it has seen any traffic at all. Possibly replacing that check with a comparison between the creation timestamp and the last update timestamp could serve the same purpose while ignoring the lack of traffic.
