### ISSUE TITLE
CentOS 7 - very outdated version in EPEL repo

### ISSUE THREAD

**Issue by nunoperalta** [vergoh/vnstat#194]
Hello,

I installed vnstat on CentOS 7 using yum, from EPEL.

The version installed seems to be `vnStat 1.15`.
However, I see there have been loads of releases since, and this version is from 2015.

Is there a reason why the version in EPEL is so old, and is there a more maintained repo?

I understand I can build manually, but I'd like to avoid having to do that on every new release.

Thank you.

**Comment by vergoh** [comment]
I suspect that (but I can be wrong) EPEL 7 may no longer be updated as EPEL 8 also exists and looking from https://repology.org/project/vnstat/versions the latest version is available there. For Red Hat / Fedora / CentOS packaging, the correct issue tracker to ask for more information is https://bugzilla.redhat.com/ as I'm not the binary package maintainer of any distribution.

**Comment by nunoperalta** [comment]
Version 1.15 doesn't even seem to work at all. Left it overnight, and only created errors in syslog, and didn't really log anything.
Can't understand why CentOS keeps such old/broken version in their repos, all the time.

Compiled now 2.6 and works perfectly. Thank you very much!
