### ISSUE TITLE
Is it possible to keep fiveminute/hour data for longer?

### ISSUE THREAD

**Issue by wanecek** [vergoh/vnstat#202]
I would like to keep more fine-grained statistics on what vnstat collects, whereas it seems like vnstat today only keeps fiveminute stats for 48 hours. I trust hat this is great for most users, as it keeps the database file small.

I'm wondering if it's possible to configure vnstatd to store fine-grained data for a longer period of time? I couldn't find afield in the config file that seems to do just this, nor when searching in the man page, but I may have glanced over something obvious.

**Comment by wanecek** [comment]
Of course, I found it as soon as I had posted this issue - my bad. Sorry for the noise.

https://github.com/vergoh/vnstat/blob/master/cfg/vnstat.conf#L91-L96

**Comment by vergoh** [comment]
The default values are currently about double of what the 1.x versions had for data retention. That keeps the database size reasonable while providing the possibility of having at least some use for the new `--begin` and `--end` query options. Also much longer retention durations have been tested without any noticable difference in performance. Note that sqlite always pre-allocates some extra space in the database file when its getting close to having the allocated size used so the database file size growing in increments is to be expected.

**Comment by wanecek** [comment]
Yeah, no worries! It turned out that I had indeed set the values, but failed to point the `--conf` file correctly, and then forgot about it. So after two weeks of running measurements, I realized I hadn't collected the data with sufficient granularity - d'oh! My bad. It seems to be working now though, so it's fine. Thanks for maintaining a great and very useful tool!
