### ISSUE TITLE
5MinuteGraphResultCount issues

### ISSUE THREAD

**Issue by thelounge-zz** [vergoh/vnstat#203]
with 2.7 you issue "Config: 5MinuteGraphResultCount has been reset to 144 due to request being larger than data retention configured with 5MinuteHours" and not only in logs at starzing the daemon but all the time

well, when you then set it to 144 it becomes headaching given that you first cry 144 is an invalid value, reset it to 576 for whatever reason followed by set it again to 144

[root@firewall:~]$ vnstat
Config: Invalid value for 5MinuteGraphResultCount, resetting to "576".
Config: 5MinuteGraphResultCount has been reset to 144 due to request being larger than data retention configured with 5MinuteHours

-----------------------

# data retention
5MinuteGraphResultCount 144
5MinuteHours  12
DailyDays     60
HourlyDays    30
MonthlyMonths 24
YearlyYears   50
TopDayEntries 10

**Comment by vergoh** [comment]
Thanks for this report.

It looks like there's a validation check missing or broken for `5MinuteHours` which is currently allowed to be anything equal or greater than -1. However, `5MinuteGraphResultCount` has a minimum of 288 as I recall the graph didn't look nice with less results causing the real minimum for `5MinuteHours` to be 24. As you've set `5MinuteHours` to 12, the version 2.7 implementation realizes that the maximum number of results that can be provided is 12 * 12 = 144 which then causes that somewhat confusing situation.

The workaround would be to set `5MinuteHours` as 24 and `5MinuteGraphResultCount` as 288 if the default values aren't suitable for your use and you still want to keep the 5 minute resolution data available.
