### ISSUE TITLE
";" in new version

### ISSUE THREAD

**Issue by Hulxv** [vergoh/vnstat#220]
In new version (2.9), Using semicolon in configuration file to comment in addition to hashtag or to select configuration props ?

**Comment by vergoh** [comment]
Both `;` and `#` act as comment characters. If either is the first character on the configuratin file line then that line gets ignored (= it's not active, changing the value does nothing). Remove the `;` for the beginning of the line to activate the option (as it says in the beginning of the file - https://github.com/vergoh/vnstat/blob/master/cfg/vnstat.conf#L4).

**Comment by Hulxv** [comment]
Ok, I got it.
Thanks a lot, I will try to support that in Client.

**Comment by vergoh** [comment]
If you want to keep things simple then you can just remove every `;` from the configuration file before initial startup of the daemon. That's pretty much how one of the test cases is currently testing the configuration file.
