### ISSUE TITLE
Interfaces ppp*

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vergoh/vnstat#222]
I have a VPS with an interface eth0 and vnstat, it gets its metrics perfectly, but not the ppp virtual interfaces created by a setup-ipsec-vpn https://github.com/hwdsl2/setup-ipsec-vpn .

Is this my mistake or is it not implemented?

**Comment by AnonymousWebHacker** [comment]
Fixed
`ifconfig`
` vnstat --add -i ppp0`

**Comment by vergoh** [comment]
The daemon automatically starts monitoring those interfaces that are available during its initial startup. Any interface that gets configured later will by default need to be manually added with the `vnstat --add -i` command as you did already found. The daemon's default behavior can be changed if started with `--noadd` or `--alwaysadd` parameters.

For listing available interfaces `vnstat --iflist` can also be used. In a similar way `vnstat --dbiflist` will provide a list of interfaces currently in the database. Both parameters support an additional mode option in case you'd want to use the output in some script in which case the output becomes one interface per line without anything extra.

**Comment by AnonymousWebHacker** [comment]
Really well explained, thanks for your time
