### ISSUE TITLE
vnStat JSON

### ISSUE THREAD

**Issue by TechKat** [vergoh/vnstat#23]
I am using the --json parameter to output results for my website's dashboard. Using a script that converts the output into a readable format, it returns MB, rather than GB. The readable numbers are the exact same.

My question is, is the rx and tx numbers bytes?

**Comment by TechKat** [comment]
No matter, I found a solution. I just had to add ```* 1024``` to the code.

**Comment by vergoh** [comment]
The rx and tx numbers are indeed always in bytes in the json and xml outputs.
