### ISSUE TITLE
BUILD FAIL: configure cannot guess build type

### ISSUE THREAD

**Issue by xctan** [vergoh/vnstat#239]
The config.guess file contains in the source code is too old that fail to build on latest architecture, such as RISC-V. This can be fixed by generating new tarball by latest autotools.

**Comment by vergoh** [comment]
The autotools generated files provided with the source code are there for ease of use and nothing blocks users from generating the files with a more recent version of autotools when necessary (as you appear to have found). Currently those will get updated whenever the autotools version in Ubuntu LTS (the distribution that I use in my development environment) changes so around every 2 years.
