### ISSUE TITLE
Pfsense retention

### ISSUE THREAD

**Issue by marc115uk** [vergoh/vnstat#241]
Have installed via package manager on pfsense, after a reboot of pfsense all my data has gone. Is there a way to retain this data after a reboot? Thanks

**Comment by vergoh** [comment]
I don't have a pfsense setup running myself but a quick search found this issue report: https://redmine.pfsense.org/issues/11797

Most likely the configuration you are having has the /var/lib/vnstat directory used by the database on a ramdisk which results in the data getting lost on every reboot. The fix would either be to reconfigure the system to keep /var/lib/vnstat permanently on some non-ramdisk location or reconfigure vnstat.conf to have the database in some other directory that's not a ramdisk.
