### ISSUE TITLE
vnstat: no longer works after databases/sqlite3 disabled DQS

### ISSUE THREAD

**Issue by joeroback** [vergoh/vnstat#243]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269966

causing issues on FreeBSD and other systems like OPNsense (based on FreeBSD).

FreeBSD bug has an attachment bug fix

**Comment by vergoh** [comment]
The test suite (`make check`) of affected vnStat releases (past releases included) will fail if DQS wasn't enabled so the status can be tested without install. The committed refactoring of queries causing the issue has been tested starting from SQLite version 3.6.22 without causing backwards incompatible side effects. DQS doesn't affect the database structure so this correction doesn't require any vnStat database updates.
