### ISSUE TITLE
How to install latest version?

### ISSUE THREAD

**Issue by Hongbo-Miao** [vergoh/vnstat#252]
I am using Ubuntu 22.04.

I found latest vnstat version in apt is 2.9.

```shell
$ apt show vnstat
Package: vnstat
Version: 2.9-1
Priority: optional
Section: universe/net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Christian Göttsche <cgzones@googlemail.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 292 kB
Pre-Depends: init-system-helpers (>= 1.54~)
Depends: adduser, lsb-base, libc6 (>= 2.34), libsqlite3-0 (>= 3.7.6.1)
Suggests: vnstati
Homepage: https://humdi.net/vnstat/
Download-Size: 103 kB
APT-Manual-Installed: yes
APT-Sources: http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages
Description: console-based network traffic monitor
 vnStat is a network traffic monitor for Linux. It keeps a log of
 daily network traffic for the selected interface(s). vnStat is not
 a packet sniffer. The traffic information is analyzed from the /proc
 filesystem, so vnStat can be used without root permissions.
```

Also, I checked vnstat is not in snap package list.

I am wondering if possible to publish latest 2.10 package to apt or snap? Or any other recommended way to install latest version? Thanks! ☺️

BTW, thanks for this awesome tool. So easy to use!

**Comment by vergoh** [comment]
You have several options depending on the level of install complexity and how "clean" you'd want the end result to be. The following aren't in any specific order:

1. Using the source package, upgrade the new version on top of the existing without removing the Ubuntu package first. Essentially this would only overwrite the binary files with the new version leaving apt to still think 2.9 is installed. The downside it that if there would for some reason be a minor update of the Ubuntu package (say 2.9-1 -> 2.9-2) then that would overwrite the version back to 2.9 and you'd need to repeat the process.

2. Same as 1 but uninstall the apt installed version first while keeping the database (which you may want to backup as I can't remember if the package uninstall removes the database directory by default). This way you don't have the (rather low risk) of apt downgrading the version during some system upgrade but, on the other hand, you'll need to manage the systemd file yourself (but that's documented in the install instructions for example: https://github.com/vergoh/vnstat/wiki/Install-in-Ubuntu )

3. Backport the package from a more recent Ubuntu release where 2.10 is likely to already be present. Assuming there aren't any packaging dependency changes, it should be enough to have the build dependencies installed, extracting the source and Ubuntu patch packages and then invoking the build which would the result in a .deb package file that can be used to upgrade the current 2.9-1 to 2.10. If 2.9-2 would then end up getting released, that wouldn't result in 2.10 getting downgraded. However, once 2.11 is released then there will again be some delay before the distribution specific packages are available, which is something you may or may not see as a downside depending on your needs.

4. Migrate to use the docker image: https://github.com/vergoh/vnstat-docker - It does have support for arm64 (which you appear to be using), is likely to be the easiest to upgrade later for new releases and can be configured to start with or without that httpd providing the image output depending on your needs. If you like to use the command line then from ease of use point of view you could alias the `vnstat` command to execute `docker exec vnstat vnstat`.

As for snap, flatpak or appimage, I haven't really investigated those options but I suspect those would prefer to sandbox the process as much as possible and are likely to limit the access to kernel interfaces vnStat requires for getting the interface details and traffic tracking.

**Comment by Hongbo-Miao** [comment]
It would be great to update the version to latest in apt (not sure if author have control). Or [publish](https://snapcraft.io/docs/creating-a-snap) to snap store. Then we don't need to compile ourselves. Thanks @vergoh !  ☺️

**Comment by vergoh** [comment]
Based on my understanding of the package release process in Ubuntu, none of the packages in the `universe` section will get any version updates once the Ubuntu distribution release has been done. The only exceptions are security updates and those can result only in minor changes like the -1 version becoming -2 either directory by some patch being needed in the package or some build dependency requiring a rebuild. If you'd want to use more recent versions then you'd need to use more recent Ubuntu distribution releases, currently published twice per year. With LTS releases you are kind of stuck with specific versions for two years at time.

As for how my vnStat releases get to Ubuntu, the flow goes somewhat like this:

1. I make a release
2. Either the Debian package maintainers notice it directly or the about once per week new release poller sends them a notification
3. They create a new version of the Debian package and then request a Debian Developer to approve the upload of the new package to Debian unstable
4. After some time in unstable the package gets migrated to Debian testing (can be followed for example from https://tracker.debian.org/pkg/vnstat), this step may get delayed if Debian is having a feature freeze period
5. If there's no [Debian Import Freeze](https://wiki.ubuntu.com/DebianImportFreeze) ongoing in Ubuntu the package will eventually get picked up by import automation and included for the next release, if the import freeze is ongoing then the package will have to wait for the following release

**Comment by Hongbo-Miao** [comment]
Thank you much for explaining, @vergoh !
I am kind of curious about how **htop** always keep up-to-date in the snap store: https://snapcraft.io/htop

**Comment by vergoh** [comment]
It looks like the htop dev team (https://github.com/htop-dev/htop) isn't responsible for the snap package but instead there's a developer from Canonical (which happens to be the same company behind snap and Ubuntu) providing the necessary setup for the snap package: https://github.com/maxiberta/htop-snap

I can't see directly from that repository if there's some automation being used for creating the releases every time a new htop version is released and then pushing that content to the snap store or is that all done manually.

**Comment by Hongbo-Miao** [comment]
Oh, I see. You are right! https://github.com/maxiberta/htop-snap is maintained by another person.
