### ISSUE TITLE
centos9 cannot be used out of the box

### ISSUE THREAD

**Issue by iloveuaa** [vergoh/vnstat#264]
Install script:
```bash
wget https://humdi.net/vnstat/vnstat-latest.tar.gz
tar zxvf vnstat-latest.tar.gz
cd vnstat-*
./configure --prefix=/usr --sysconfdir=/etc && make && make install
sed -i 's|;DatabaseDir "/var/lib/vnstat"|DatabaseDir "/www/db"|' /etc/vnstat.conf
cp -v examples/systemd/vnstat.service /etc/systemd/system/
systemctl enable vnstat
systemctl start vnstat
```
After the command is executed, the corresponding process cannot be found in the process. You need to use `vnstatd --initdb` first and then manually execute `vnstatd -n` to get data. The service script cannot be used normally

**Comment by vergoh** [comment]
Could you clarify for reference to possible future readers if the issue was with that `sed` command that's changing the `DatabaseDir` in the configuration file?
