### ISSUE TITLE
Centos9 failed to run after compilation

### ISSUE THREAD

**Issue by iloveuaa** [vergoh/vnstat#265]
script:
```
wget https://humdi.net/vnstat/vnstat-latest.tar.gz
tar zxvf vnstat-latest.tar.gz
cd vnstat-*
./configure --prefix=/usr --sysconfdir=/etc && make -j16 && make install
cp -v examples/systemd/vnstat.service /etc/systemd/system/
sudo systemctl enable vnstat
sudo systemctl start vnstat
```

show:
[root@150S1848 vnstat-2.12]# ps -ef|grep vnstat
root       61450   18575  0 16:55 pts/0    00:00:00 grep --color=auto vnstat

centos7:
In centos7, you can see the daemon process

**Comment by iloveuaa** [comment]
![image](https://github.com/user-attachments/assets/82c8b6f2-d989-4a41-9e3b-0323dbd4bb7d)
I executed `sudo systemctl enable vnstat` to generate `vnstatd` and then executed the corresponding service but it still did not run successfully.

**Comment by iloveuaa** [comment]
![image](https://github.com/user-attachments/assets/7ae999b0-8bdc-4df7-a33f-1f16623ebd82)
The first manual run will get stuck, then it will succeed after interruption and then execution again

**Comment by vergoh** [comment]
I've verified with a fresh CentOS 9 install that the "CentOS 7 and later" install instructions in https://github.com/vergoh/vnstat/wiki/Install-in-CentOS do work correctly with CentOS 9 too.

Based on your current version of "script" (which doesn't anymore have the `sed` command it had earlier), I suspect things go wrong at least in the `make install` part if you aren't root at that point as `sudo` is being used later. If `systemctl start vnstat` doesn't result in a running daemon then `systemctl status vnstat` should give some clues what's going wrong.

**Comment by iloveuaa** [comment]
> I've verified with a fresh CentOS 9 install that the "CentOS 7 and later" install instructions in https://github.com/vergoh/vnstat/wiki/Install-in-CentOS do work correctly with CentOS 9 too.
> 
> Based on your current version of "script" (which doesn't anymore have the `sed` command it had earlier), I suspect things go wrong at least in the `make install` part if you aren't root at that point as `sudo` is being used later. If `systemctl start vnstat` doesn't result in a running daemon then `systemctl status vnstat` should give some clues what's going wrong.

thanks for your reply.
After the installation was complete, I modified the configuration file, changed the path of the db location, I was the root account, and added corresponding permissions to the db path.

```bash
[root@150S001 custom]# systemctl status vnstat
× vnstat.service - vnStat network traffic monitor
     Loaded: loaded (/etc/systemd/system/vnstat.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2024-09-29 14:51:41 CST; 2min 29s ago
   Duration: 44ms
       Docs: man:vnstatd(8)
             man:vnstat(1)
             man:vnstat.conf(5)
    Process: 80128 ExecStart=/usr/sbin/vnstatd -n (code=exited, status=1/FAILURE)
   Main PID: 80128 (code=exited, status=1/FAILURE)
        CPU: 44ms

Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Scheduled restart job, restart counter i>
Sep 29 14:51:41 150S1848 systemd[1]: Stopped vnStat network traffic monitor.
Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Start request repeated too quickly.
Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Failed with result 'exit-code'.
Sep 29 14:51:41 150S1848 systemd[1]: Failed to start vnStat network traffic monitor.

[root@150S1848 custom]# journalctl -xe -u vnstat.service
░░ The job identifier is 16467 and the job result is done.
Sep 29 14:51:39 150S1848 systemd[1]: Started vnStat network traffic monitor.
░░ Subject: A start job for unit vnstat.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit vnstat.service has finished successfully.
░░ 
░░ The job identifier is 16467.
Sep 29 14:51:39 150S1848 vnstatd[80128]: Error: Failed to open database "/www/db/vnstat.db" >
Sep 29 14:51:39 150S1848 vnstatd[80128]: Exiting...
Sep 29 14:51:39 150S1848 systemd[1]: vnstat.service: Main process exited, code=exited, status>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStart= process belonging to unit vnstat.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 29 14:51:39 150S1848 systemd[1]: vnstat.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit vnstat.service has entered the 'failed' state with result 'exit-code'.
Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Scheduled restart job, restart counter i>
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ Automatic restarting of the unit vnstat.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Sep 29 14:51:41 150S1848 systemd[1]: Stopped vnStat network traffic monitor.
░░ Subject: A stop job for unit vnstat.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit vnstat.service has finished.
░░ 
░░ The job identifier is 16567 and the job result is done.
Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Start request repeated too quickly.
Sep 29 14:51:41 150S1848 systemd[1]: vnstat.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit vnstat.service has entered the 'failed' state with result 'exit-code'.
Sep 29 14:51:41 150S1848 systemd[1]: Failed to start vnStat network traffic monitor.
░░ Subject: A start job for unit vnstat.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit vnstat.service has finished with a failure.
░░ 
░░ The job identifier is 16567 and the job result is failed.

```

i try execute `vnstatd --initdb`  but is failed.
I tried executing the command several times `vnstatd -n`  after is restart is running.
I don't know the reason.

I followed the URL（https://github.com/vergoh/vnstat/wiki/Install-in-CentOS ） you sent and the operation was successful. The only difference was that I changed the db path.

**Comment by iloveuaa** [comment]
> I've verified with a fresh CentOS 9 install that the "CentOS 7 and later" install instructions in https://github.com/vergoh/vnstat/wiki/Install-in-CentOS do work correctly with CentOS 9 too.
> 
> Based on your current version of "script" (which doesn't anymore have the `sed` command it had earlier), I suspect things go wrong at least in the `make install` part if you aren't root at that point as `sudo` is being used later. If `systemctl start vnstat` doesn't result in a running daemon then `systemctl status vnstat` should give some clues what's going wrong.

Thanks for your replay. I executed the sed command to modify the configuration file after compiling and installing it. This time I tried to modify it manually and the result was successful.

**Comment by iloveuaa** [comment]
Although the operation was successful and you can see `/usr/sbin/vnstatd -n`, the database was not generated. After regenerating it using `vnstatd --initdb` and restarting the service, it still prompts "Error: Database is empty."

**Comment by vergoh** [comment]
Essentially what you are trying to get working is to have the installed and systemd started vnStat use a different database directory?

If that's the case then there are possibly few aspects of this problem:

1. systemd hardening
2. SELinux in CentOS 9

The service file `examples/systemd/vnstat.service` you've selected enables many kinds of hardenings for the vnStat daemon and also defines which directories it's allow to write to. If the database directory is changes then these would also need to be changed in the service file.

Then there's SELinux that appears to be enabled by default in CentOS 9. I tested using even the non-hardened service file from `examples/systemd/simple/vnstat.service` and even that fails to write to the database if the database directory is in some location SELinux doesn't tolerate (I tested with `/opt`). However, if SELinux is turned from the default `Enforcing` mode to `Permissive` mode then that same service file starts working. You'd need to consult the CentOS documentation related to SELinux in order to understand what are the default directories systemd started services are allowed to use and how to adjust those if you'd want to use a non-standard directory with the OS you've chosen with SELinux enabled or just use the default database directory since it's been verified to work correctly.

**Comment by iloveuaa** [comment]
> Essentially what you are trying to get working is to have the installed and systemd started vnStat use a different database directory?
> 
> If that's the case then there are possibly few aspects of this problem:
> 
> 1. systemd hardening
> 2. SELinux in CentOS 9
> 
> The service file `examples/systemd/vnstat.service` you've selected enables many kinds of hardenings for the vnStat daemon and also defines which directories it's allow to write to. If the database directory is changes then these would also need to be changed in the service file.
> 
> Then there's SELinux that appears to be enabled by default in CentOS 9. I tested using even the non-hardened service file from `examples/systemd/simple/vnstat.service` and even that fails to write to the database if the database directory is in some location SELinux doesn't tolerate (I tested with `/opt`). However, if SELinux is turned from the default `Enforcing` mode to `Permissive` mode then that same service file starts working. You'd need to consult the CentOS documentation related to SELinux in order to understand what are the default directories systemd started services are allowed to use and how to adjust those if you'd want to use a non-standard directory with the OS you've chosen with SELinux enabled or just use the default database directory since it's been verified to work correctly.

Thanks for your replay.
I currently want to modify the db path after the installation is complete, and then run it automatically on the first startup, but it fails. my selinux set disable.
![image](https://github.com/user-attachments/assets/2d8542ac-3666-4c8c-8596-84b587709def)

After enabling the service, a startup service will be generated. The contents of the two scripts are the same.
![image](https://github.com/user-attachments/assets/c66e7a8b-70e2-47b1-90d0-cd6f01e94a97)

**Comment by iloveuaa** [comment]
If I do not modify the db path and run it directly after installation, it will run normally.

**Comment by iloveuaa** [comment]
I have authorized this directory. 
```
Sep 27 16:45:55 150S1848 vnstatd[58584]: Error: Exec step failed (8: attempt to write a readonly database): "update info set value='2.12' where name='vn>
Sep 27 16:45:55 150S1848 vnstatd[58584]: Error: Failed to open database "/www/db/vnstat.db" in read/write mode.
Sep 27 16:45:55 150S1848 vnstatd[58584]: Exiting...
```

**Comment by vergoh** [comment]
Have you tried by using `examples/systemd/simple/vnstat.service` (note `simple` in the directory path)?
That service file doesn't have any systemd related hardenings enabled so if it works while SELinux is disabled then the issue was related to systemd configuration. If that still doesn't work then the issue is still with SELinux.

**Comment by iloveuaa** [comment]
> Have you tried by using `examples/systemd/simple/vnstat.service` (note `simple` in the directory path)? That service file doesn't have any systemd related hardenings enabled so if it works while SELinux is disabled then the issue was related to systemd configuration. If that still doesn't work then the issue is still with SELinux.

yes thanks.
