### ISSUE TITLE
Error: Unable to open database for writing: Permission denied

### ISSUE THREAD

**Issue by mmagdy88** [vergoh/vnstat#42]
This happens for every installation and the fix would be

chown vnstat: /var/lib/vnstat/*

OS: CentOS 6 & 7
Installed using yum.

**Comment by vergoh** [comment]
That appears to be a distribution packaging related issue. I assume that the package in CentOS comes from EPEL. In that case, the report should be done via https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora+EPEL
