### ISSUE TITLE
Question: set first day of the month

### ISSUE THREAD

**Issue by jsumners** [vergoh/vnstat#43]
Is there any way to change the "first day of the month" for vnstat? Example:

```
$ vnstat -m

 external (enp4s0)  /  monthly

       month        rx      |     tx      |    total    |   avg. rate
    ------------------------+-------------+-------------+---------------
      May '16     45.71 GiB |    1.86 GiB |   47.57 GiB |  148.99 kbit/s
      Jun '16    261.80 GiB |    4.57 GiB |  266.36 GiB |    1.26 Mbit/s
    ------------------------+-------------+-------------+---------------
    estimated    381.14 GiB |    6.64 GiB |  387.79 GiB |
```

As you can see, *vnstat* is treating the first day I started the daemon as the first day of the month. I need it to be the actual first day, e.g. for June it should start at June 1.

My `/etc/vnstat.conf` has `MonthRotate 1` set, but that doesn't seem to have any effect.

```
$ vnstat -v
vnStat 1.15 by Teemu Toivola <tst at iki dot fi>
```

**Comment by vergoh** [comment]
What was the output you were expecting? I'm not sure that I can see the difference of the first day of the month from that output you've shown. ``MonthRotate 1`` is the default value.

**Comment by jsumners** [comment]
I think I'll just learn to read. I was totally missing that `'16` is the abbreviation for `2016`. I was reading it as "the sixteenth day of May/June".
