### ISSUE TITLE
Remote control / access

### ISSUE THREAD

**Issue by apax0r** [vergoh/vnstat#44]
Would be nice to have remote controll of vnstat so you can collect data from diffrent hosts!

Such as in FreeNAS jails or other simular setups.

Sorry bad english!

**Comment by vergoh** [comment]
How do you see that the necessary data for vnStat on those other hosts would be made accessible?

Would the all hosts be running vnstatd and then the main host would be responsible for collecting the data via some tcp/udp port that the vnstatd on other hosts would be listening? Or would those other hosts rather expose the data via snmp or something similar?

**Comment by vergoh** [comment]
Feel free to reopen with more details. There are already ways to access data remotely using existing releases.
