### ISSUE TITLE
Traffic from apt-mirror not counted

### ISSUE THREAD

**Issue by markus-k** [vergoh/vnstat#45]
I noticed traffic from [apt-mirror](https://apt-mirror.github.io/) is not (reliably) counted by vnstat, but the traffic shows up in my Zabbix monitoring. apt-mirror downloaded a good 120GB at a speed of roughly 700Mbit/s today, yet only 18GB were registered by vnstat (which includes other traffic by other applications). I haven't noticed any other applications not being counted on my system. I have no idea how this is even possible, vnstat usually even counts routed traffic on the network interface. Any suggestions?

**Comment by vergoh** [comment]
Which version is in question?
Is the daemon being used or a cron entry for updates?
What is the value of ``MaxBandwidth`` in /etc/vnstat.conf? (this is the most likely cause)

**Comment by markus-k** [comment]
Version is 1.12, the daemon is used. `MaxBandwidth` is a good pointer, was set to 100, thank you. I set it to 1000, I'll keep an eye on it if traffic is counted properly now.

**Comment by vergoh** [comment]
Remember to restart or at least reload the daemon. Otherwise, changing the value will not have any effect.

**Comment by markus-k** [comment]
Looks like this was the problem.
