### ISSUE TITLE
PollInterval Range Incorrect

### ISSUE THREAD

**Issue by NoSuck** [vergoh/vnstat#46]
... either that, or the documentation is incorrect.

I am just getting into vnstat and think I am going to love it.  In setting up the initial configuration, I noticed that PollInterval was capped at 60 instead of 300 as listed in the documentation.

Thank you!

**Comment by vergoh** [comment]
Thanks, that's a valid finding. Looking at the change history, ``PollInterval`` has always been capped to 60. The mistake was made when the value ranges were later added to the documentation and ``PollInterval`` got marked with a 300 cap for some reason.

**Comment by vergoh** [comment]
All the other documented value ranges appear to be correct.
