### ISSUE TITLE
Text Width Miscalculation

### ISSUE THREAD

**Issue by NoSuck** [vergoh/vnstat#49]
Vnstat has made my day.  I configured it just right, started the daemon, and waited patiently for data to amass in each interface's database.

I then noticed graph columns did not align correctly:

![Text Width Miscalculation](https://nosuckdotorg.files.wordpress.com/2016/10/vnstat-character-width-miscalculation.png)

I've encountered this problem in my own programs.  As programmers, we cannot assume that characters of localized strings only occupy a single column.  The fix is straightforward and begins with the man page for wcswidth().

Thank you for maintaining such an awesome utility.

**Comment by vergoh** [comment]
Which version of vnStat are you using? That issue looks the same as #20 that's already been solved.

**Comment by NoSuck** [comment]
Thank you for the information.  I am using 1.15 on Arch Linux and see calls to `getpadding()` in the source.  Perhaps the misalignment occurs because a plain `strlen()` is called on `datebuff` in `showdays()`?  I cannot tell for sure.
