### ISSUE TITLE
Coverity Scan

### ISSUE THREAD

**Issue by cgzones** [vergoh/vnstat#50]
Can you consider adding vnstat to Coverity Scan.

**Comment by vergoh** [comment]
Thanks for reminding me of Coverity Scan. I did notice it some years ago but either it wasn't open for small projects back then or the documentation just wasn't what it appears to be today as I don't recall having investigated using it any further.

Anyway, I've added vnStat to Coverity Scan and it's currently waiting for some sort of review before I get to see what sort of findings the scan is producing.

**Comment by cgzones** [comment]
Thanks for your effort and this whole great tool.
