### ISSUE TITLE
Edit database

### ISSUE THREAD

**Issue by Zekario** [vergoh/vnstat#61]
I've been doing some weird stuff and it's messed with my vnstat output. I realized this when I had already uploaded three gigabytes abnormally. Can I edit the database to return the value for a specific hour to a sensible size? I don't know what format databases are in, or how to open them.

**Comment by vergoh** [comment]
1. stop the service (``vnstatd``)
2. make sure it really is stopped :)
3. ``vnstat --exportdb -i your_interface >tempfile``
4. modify that tempfile, see ``man vnstat`` for details
5. ``vnstat --importdb tempfile -i your_interface``
6. restart the service
