### ISSUE TITLE
How do I get vnstatd to monitor all interfaces?

### ISSUE THREAD

**Issue by martinvonwittich** [vergoh/vnstat#66]
Hi,

according to the docs, `vnstatd` will only create database files for interfaces when there aren't any files yet. How do get it to automatically create database files for interfaces that are added later on? Is there an option for that?

**Comment by vergoh** [comment]
A parameter for the daemon exists for achieving that functionality. The ``vnstatd`` man page says:

>        --alwaysadd
>               Enable automatic creation of new databases for previously unseen interfaces even if the database  directory  already  con‐
>               tains  databases  when the daemon is started. New databases will also get created for new interfaces seen while the daemon
>               is running. Pseudo interfaces lo, lo0 and sit0 are excluded from getting added.

Add that to the parameters given for the daemon during its startup and restart it if already running. This feature was added in version 1.15.

**Comment by martinvonwittich** [comment]
Ah, OK. We're still running Debian jessie with vnstat 1.12. I've written the following short script to work around the issue:

```
#!/bin/sh

RESTART=0

ip link show | perl -ne '/^\d+: (eth\d+):/ && print "$1\n"' | while read IF
do
  if [ ! -f /var/lib/vnstat/"$IF" ]
  then
    vnstat -i "$IF" -u
    RESTART=1
  fi
done

if [ "$RESTART" -eq 1 ]
then
  chown vnstat:vnstat /var/lib/vnstat/*
  systemctl restart vnstat
fi
```
