### ISSUE TITLE
[question] having stats for any sub interface ( eth0:1 , eth0:2 ... ) ?

### ISSUE THREAD

**Issue by jsaada** [vergoh/vnstat#67]
hello,
thanks for this great software !
i'm using vnStat 1.12 on debian jessie and didn't see anything about what i'm looking for:
i ve got several logical interface, and i need details per sub-interface
eth0 
eth0:1
eth0:2 

is that possible ?

**Comment by vergoh** [comment]
``man vnstat`` and the RESTRICTIONS chapter explain why those sub-interfaces can't be monitored by vnStat:
>        Virtual and aliased interfaces cannot be monitored because the kernel doesn't provide traffic information for that type of inter‐
>        faces. Such interfaces are usually named eth0:0, eth0:1, eth0:2 etc. where eth0 is the actual interface being aliased.

**Comment by jsaada** [comment]
indeed ...
thanks for your reply
