### ISSUE TITLE
Will upgrading vnstat result in any loss of logs/database/stats?

### ISSUE THREAD

**Issue by hub2git** [vergoh/vnstat#68]
My router with LEDE  (version 17.01.2) has vnstat version 1.12. I could upgrade it to vnstat version 1.17 by following instructions on https://forum.lede-project.org/t/why-vnstat-is-at-version-1-12-1-only/1179/21

My Linux Mint 18.2 Xfce  has vnstat version 1.14. I could follow the instructions on https://askubuntu.com/questions/938293/update-vnstat-to-1-17 to upgrade to vnstat 1.17.

Here's my question. If I upgrade the vnstat on my Linux Mint computer or my router, will I lose some vnstat data/logs/stats that are being saved?

Another question: Before I can upgrade to vnstat 1.17, wouldn't I first have to remove my current vnstat? If so, am I right to think that uninstalling would remove all the vnstat logs/stats/database?

**Comment by vergoh** [comment]
Upgrade directly from both versions 1.12 and 1.14 to version 1.17 is supported without losing data. Based on a quick check, neither of those linked instructions do anything destructive either. However, it depends on how the distribution packaging has been done regarding what gets removed when the package is uninstalled. It doesn't hurt to take a backup of the database files. Note that the configuration file contains new options so check those out and tune if needed. See the UPGRADE file that comes with the source package for a list of new settings and ``man vnstat.conf`` for a description of what those settings do.

**Comment by hub2git** [comment]
Thanks, Vergoh. I'll close this issue. I haven't upgraded yet. If I have issues with data loss, I may reopen this issue. :)

**Comment by hub2git** [comment]
@vergoh said
>  It doesn't hurt to take a backup of the database files. 

Should I do so my simply copying the relevant files and folders to my backup location? If so which files and folders should I copy?

Or do you suggest using the `--exportdb` option? If so, I'm a bit worried, because http://humdi.net/vnstat/CHANGES says 

> 1.17 / 16-Feb-2017
> 
>  - Fix: --importdb was creating invalid databases since version 1.15

**Comment by hub2git** [comment]
Another question, what happens if I upgrade to vnstat 2.0? Any loss of database/logs/info?

**Comment by vergoh** [comment]
During the first daemon startup of version 2.x, all found version 1.x databases get automatically imported to the version 2.x database. Because the new database is a single file for all interfaces, the old version 1.x database files are kept in place, just in case the user wants to downgrade for some reason. Nothing is lost during the import process.
