### ISSUE TITLE
wrong accouting inside guest after virsh snapshot-create-as

### ISSUE THREAD

**Issue by localguru** [vergoh/vnstat#77]
Hi,

for backup reasons I run a `virsh snapshot-create-as` on a KVM guest, which takes a few seconds. After deleting the domain snapshot, vnstat accounts a difference of several GB traffic, which is incorrect. ifconfig doesn't show any significant difference. I tried to disable the ens3 interface with `/usr/bin/vnstat -u -r --disable -i ens3`, but that doesn't help either, as well as a --sync. Any ideas?

before virsh snapshot-create-as
```
/usr/bin/vnstat -u -r --disable -i ens3
date: Do 28. Sep 02:35:01 CEST 2017
ifconfig: RX-Bytes:1567747617 (1.5 GB)  TX-Bytes:5697839487 (5.6 GB)
vnstat: h;2;1506558901;10111;2789
```

after virsh snapshot-delete
```
/usr/sbin/ntpdate -u -s ptbtime1.ptb.de ptbtime2.ptb.de (adjust time server 192.53.103.108 offset 0.036872 sec)
/usr/bin/vnstat -u -r --enable -i ens3
date: Do 28. Sep 02:37:14 CEST 2017
ifconfig: RX-Bytes:1567904861 (1.5 GB)  TX-Bytes:5698030537 (5.6 GB)
vnstat: h;2;1506559034;1541268;5567271 <---- WRONG
```
vnstat -v: vnStat 1.14 by Teemu Toivola <tst at iki dot fi>
```
BandwidthDetection 1
MaxBandwidth 1000
```
System: Ubuntu 16.06 LTS
Kernel: Linux server 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[vnstat.conf.txt](https://github.com/vergoh/vnstat/files/1343296/vnstat.conf.txt)

May be similar to #69 ?

**Comment by localguru** [comment]
I started monitoring the interface on the host, which gives correct vnstat values. Inside the guest one can see a peak at 2:30h. At this time the host creates a domain snapshot on the guest. After that, vnstat inside the guest shows the peak. Ifconfig shows correct values inside the guest and on the host.

*inside guest*:
![guest](https://user-images.githubusercontent.com/8544984/31045115-bbe7df7a-a5dc-11e7-908e-7b00ed66e465.png)
```
guest:~$ vnstat -h
 ens3                                                                     11:07 
  ^                                             t                               
  |                                             t                               
  |                                             t                               
  |                                             t                               
  |                                             t                               
  |                                             t                               
  |                                            rt                               
  |                                            rt                               
  |                                            rt                               
  |                                            rt                               
 -+---------------------------------------------------------------------------> 
  |  12 13 14 15 16 17 18 19 20 21 22 23 00 01 02 03 04 05 06 07 08 09 10 11    
                                                                                
 h  rx (MiB)   tx (MiB)      h  rx (MiB)   tx (MiB)      h  rx (MiB)   tx (MiB) 
12      16,11       4,48    20      21,14      11,87    04      30,51       3,46
13      17,59       4,82    21      23,46       4,92    05      19,03       3,29
14      18,74      31,06    22      23,47       5,26    06      24,71       3,38
15      20,93       4,13    23      21,39       7,50    07      23,39       3,41
16      24,00       3,86    00      22,84       4,92    08      19,25       3,36
17      19,51       3,54    01      23,40       3,41    09      24,81       3,43
18      25,11      13,89    02   2.389,18   5.822,41    10      23,56       7,48
19      23,47       3,64    03      23,30       3,35    11       0,23       0,37
```

```
guest:~$ ifconfig ens3
[...]
RX-Bytes:2695300944 (2.6 GB)  TX-Bytes:6136712206 (6.1 GB)
```

*vnet on the host*
![host](https://user-images.githubusercontent.com/8544984/31045117-bdebbd0a-a5dc-11e7-945c-484822a2be62.png)

```
host:~$ vnstat -i vnet12 -h
 vnet12                                                                   11:07 
  ^                                                   t                         
  |                                                   t                         
  |                              t        t        t  t                         
  |                     t  t     t  t     t  t     t  t     t  t     t  t       
  |                     t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t       
  |                     t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t       
  |                     t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t  t       
  |                    rt  t rt  t  t  t  t  t  t  t  t  t  t  t  t  t  t       
  |                    rt  t rt  t  t rt  t  t  t  t  t  t  t  t  t  t rt       
  |                    rt rt rt rt rt rt rt rt rt rt rt rt rt rt rt rt rt       
 -+---------------------------------------------------------------------------> 
  |  12 13 14 15 16 17 18 19 20 21 22 23 00 01 02 03 04 05 06 07 08 09 10 11    
                                                                                
 h  rx (KiB)   tx (KiB)      h  rx (KiB)   tx (KiB)      h  rx (KiB)   tx (KiB) 
12          0          0    20      12088      20077    04       3549      31245
13          0          0    21       5092      25590    05       3400      20483
14          0          0    22       5379      24033    06       3422      24301
15          0          0    23       7595      19799    07       3492      23951
16         26         15    00       5116      25490    08       3498      21196
17       2943       1801    01       3529      23983    09       3465      23916
18      11438      24275    02       3491      19733    10       7659      24125
19       3695      24017    03       3504      25383    11        342        219
```
```
host:~$ ifconfig vnet12
[...]
RX-Bytes:6136665611 (6.1 GB)  TX-Bytes:2695271652 (2.6 GB)
```

**Comment by vergoh** [comment]
Are you using a cron entry with something like ``vnstat -u`` to keep vnStat updated or is the daemon (vnstatd) running as a service?

**Comment by localguru** [comment]
It's running as daemon:
` /usr/sbin/vnstatd -d --pidfile /run/vnstat/vnstat.pid`

**Comment by vergoh** [comment]
``vnstat -u -r --disable`` or ``--sync`` aren't going to help because both modify the database directly but the daemon is using a cached copy that will then overwrite all modifications. Ideally, there should be some way of commanding the daemon to either disable interface or sync the traffic counter. Something like a signal could work for the later but isn't implemented. It could however be a workaround to stop the daemon before then snapshot taking and then restart it after the snapshot with the ``--sync`` option.

I'm not exactly familiar regarding how virsh interacts with KVM guests. Is the KVM guest running during the snapshot procedure or is it paused? Since the interface traffic counter don't appear to reset to zero then it's not the case of vnStat assuming that the counter has overflowed. As mentioned in #69, reducing the ``UpdateInterval`` value may help but I suspect there's something else going on in this scenario. Does for example the btime value in /proc/stat in the KVM guest change during the snapshot procedure? The would cause vnStat to assume that the system has been rebooted and count the already existing counter values as new traffic.

**Comment by vergoh** [comment]
Feel free to reopen is the issue still exists.
