### ISSUE TITLE
deb package for 1.17

### ISSUE THREAD

**Issue by localguru** [vergoh/vnstat#78]
Hi,

I built an upstream package for Debian/Ubuntu, because I couldn't find any deb packages for the current version 1.17. Feel free to use it:

 https://www.binux.de/debian/xenial/vnstat/

Ciao
Marcus

**Comment by vergoh** [comment]
The official Debian package page is the following: https://tracker.debian.org/pkg/vnstat

I'd suggest contacting the current package maintainer if an update is needed. However, I suspect the some automated mail has already been sent for 1.16 and 1.17 to the maintainer as the latest release version is visible on that page. Once updated, the Debian package gets automatically migrated to Ubuntu unless there's a feature freeze ongoing.

This may actually explain why the latest version in Debian is still 1.15: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874387

**Comment by vergoh** [comment]
1.17 is now in Debian testing.
