### ISSUE TITLE
Traffic is 4 GiB rx and 4 GiB tx per day

### ISSUE THREAD

**Issue by kriztan** [vergoh/vnstat#83]
Since some weeks I recognized, that the traffic per day is sometimes not correct and vnstat is showing 4,0 GiB rx and 4,0 GB tx.  
![vnstat_daily](https://user-images.githubusercontent.com/3350754/34720533-51dd6296-f53f-11e7-8e7a-162e5a5a5e06.png)
For your information I'm running vnstat 1.17 on a raspberry pi 2 to monitor the vpn traffinc on tun0. For testing purposes I've checked the traffic on the other vpn end, which is a round about 400 - 450 MiB per day like all other days. 
The tun0 is restarted once a day via cron and the pi is online for more than 100 days without a restart. I can't replicate this behavour. 
Any ideas?

**Comment by vergoh** [comment]
``UpdateInterval`` is most likely too high. If it's still the default 30 the lower it to for example 10. If it has been increased for some reason then bring it back to the default 30. Remember to restart the daemon after any config file modifications.

**Comment by kriztan** [comment]
Thanks @vergoh, I've decreased the `UpdateInterval` from 30 to 10, but it's still happening. Shall I decrease this value a bit more? E.g. to 5 oder 2 seconds?

**Comment by vergoh** [comment]
Decreasing ``UpdateInterval`` any further isn't likely to help. The fact that setting it to 10 didn't solve the issue suggests some other setting is not optimally configured. Have a look at the following settings:

- ``BandwidthDetection`` should be 1 but I'm not 100% sure if it will work for the tun0 interface
- ``MaxBandwidth`` is the fallback setting when automatic detection doesn't work. The default may be 1000 which is likely to be too high compared to what the interface can do in reality. If the built-in ethernet interface is being used then decrease this value to 100. That's likely to solve the issue.

**Comment by kriztan** [comment]
It seems that `BandwidthDetection = 1` and `MaxBandwidth = 100` solved my problem. Since this changes I can't see this strange traffics in my graphs.
